/**
 * Curated grants/fellowships/funding dataset.
 *
 * Filtered to opportunities open to African (incl. Tanzanian) applicants:
 * worldwide/international programs, or ones explicitly open to Africa.
 * Entries restricted to a specific non-African region (a US state/city/
 * county, "U.S." only, "North America", UK, Netherlands, Australia,
 * Canada, or a specific EU-country list) were removed on 2026-09-27 after
 * user review flagged a Kentucky-only grant that had no business being in
 * an Africa-facing list — see git history for the full removed list if
 * you ever need to build a separate "US-only" board from the same source
 * research.
 *
 * Unlike the job sources in src/lib/sources/ (which hit a live public API
 * per source), most grant-making organizations don't expose one — this
 * data is manually researched (from provided links + targeted web
 * research) and kept here as a single "source" the ingestion pipeline can
 * fetch from like any other. When new opportunities are found, add a new
 * RawGrant entry to CURATED_GRANTS below (confirming it's open to African
 * applicants first) and re-run `npm run ingest:grants`.
 *
 * windowText is kept verbatim from the source — opensAt/deadline/isRolling
 * are BEST-EFFORT parses of it (see lib/grants/parse-window.ts), so the
 * original text is always shown to the user even when parsing can't
 * produce a precise date.
 */

import type { RawGrant } from "@/lib/grants/source-types";

export const CURATED_GRANTS: RawGrant[] = [
  {
    title: "Society for American Music — Hampsong Education Fellowship in American Song",
    organization: "Society for American Music",
    url: "https://hampsongfoundation.org/project/hampsongeducation-fellowship-in-american-song/",
    applicationUrl: "https://hampsongfoundation.org/project/hampsongeducation-fellowship-in-american-song/",
    category: "arts_music",
    eligibilityText:
      "Open to members of the Society for American Music at any career phase; SAM offers international membership with no citizenship restriction stated, so Tanzanian applicants can join and apply, but membership is a prerequisite (join at american-music.org before applying).",
    focusText: "Music; performance; music education; humanities",
    amountText: "Up to $1,000",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "society-for-american-music-hampsong-education-fellowship-in-american-song",
  },
  {
    title: "Awesome Foundation — Monthly Microgrants",
    organization: "Awesome Foundation",
    url: "https://www.awesomefoundation.org/en",
    applicationUrl: "https://www.awesomefoundation.org/en",
    category: "community_civic",
    eligibilityText: "Worldwide; eligibility varies by chapter",
    focusText: "Music; film; photography; visual art; community creative projects",
    amountText: "$1,000",
    windowText: "Rolling; chapters award monthly",
    sourceItemId: "awesome-foundation-monthly-microgrants",
  },
  {
    title: "Artist Grant — November 2026",
    organization: "Artist Grant",
    url: "https://artistgrant.org/apply",
    applicationUrl: "https://artistgrant.org/apply",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; visual artists age 18+",
    focusText: "Photography; painting; drawing; sculpture; ceramics; printmaking; mixed media",
    amountText: "$1,200 unrestricted",
    windowText: "Deadline: Nov 15, 2026",
    sourceItemId: "artist-grant-november-2026",
  },
  {
    title: "The Hopper Prize — Fall 2026",
    organization: "The Hopper Prize",
    url: "https://hopperprize.org/",
    applicationUrl: "https://hopperprize.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "Photography; visual art; mixed media; any medium",
    amountText: "2 × $4,500 + 4 × $1,000",
    windowText: "Deadline: Nov 17, 2026",
    sourceItemId: "the-hopper-prize-fall-2026",
  },
  {
    title: "Pollock-Krasner Foundation Grant",
    organization: "Pollock-Krasner Foundation Grant",
    url: "https://pkf.org/apply/",
    applicationUrl: "https://pkf.org/apply/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; professional painters, sculptors and artists working on paper",
    focusText: "Painting; sculpture; works on paper",
    amountText: "Up to $50,000",
    windowText: "Rolling",
    sourceItemId: "pollock-krasner-foundation-grant",
  },
  {
    title: "Adolph & Esther Gottlieb Foundation — Emergency Grant",
    organization: "Adolph & Esther Gottlieb Foundation",
    url: "https://www.gottliebfoundation.org/emergency-grant",
    applicationUrl: "https://www.gottliebfoundation.org/emergency-grant",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; mature visual artists facing a one-time catastrophic emergency",
    focusText: "Painting; sculpture; printmaking",
    amountText: "Typically up to $15,000",
    windowText: "Rolling",
    sourceItemId: "adolph-esther-gottlieb-foundation-emergency-grant",
  },
  {
    title: "ArtFundMe — Autumn 2026 Artist Grant",
    organization: "ArtFundMe",
    url: "https://artfundme.org/",
    applicationUrl: "https://artfundme.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "Visual art; photography; film; sound; mixed media; multidisciplinary",
    amountText: "$1,000",
    windowText: "Open Sep 18–Nov 20, 2026",
    sourceItemId: "artfundme-autumn-2026-artist-grant",
  },
  {
    title: ".ART Award 2026",
    organization: ".ART Award 2026",
    url: "https://art.art/award/",
    applicationUrl: "https://art.art/award/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "All visual/media disciplines",
    amountText: "Grand prize includes $15,000 cash; $50,000+ total prize value",
    windowText: "Deadline: Nov 1, 2026",
    sourceItemId: "art-award-2026",
  },
  {
    title: "PhMuseum Women Photographers Grant 2026",
    organization: "PhMuseum Women Photographers Grant 2026",
    url: "https://phmuseum.com/grants",
    applicationUrl: "https://phmuseum.com/grants",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; women and nonbinary photographers",
    focusText: "Photography",
    amountText: "€10,000 total cash grants + additional opportunities",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "phmuseum-women-photographers-grant-2026",
  },
  {
    title: "Gomma Photography Grant 2026",
    organization: "Gomma Photography Grant 2026",
    url: "https://www.gommagrant.com/",
    applicationUrl: "https://www.gommagrant.com/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide photographers",
    focusText: "Photography",
    amountText: "Top cash prize €1,000 + additional awards",
    windowText: "Final deadline: Nov 5, 2026",
    sourceItemId: "gomma-photography-grant-2026",
  },
  {
    title: "eidolon Grant 2026",
    organization: "eidolon Grant 2026",
    url: "https://www.eidoloncentre.org/",
    applicationUrl: "https://www.eidoloncentre.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide",
    focusText: "Photography; vernacular/found photography research and artistic practice",
    amountText: "€25,000 total across categories",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "eidolon-grant-2026",
  },
  {
    title: "Africa No Filter — Kekere Storytellers Fund",
    organization: "Africa No Filter",
    url: "https://africanofilter.org/grants",
    applicationUrl: "https://africanofilter.org/grants",
    category: "arts_multidisciplinary",
    eligibilityText: "Africa and African diaspora; creators under 35; see country rules",
    focusText: "Music; photography; digital storytelling; content creation",
    amountText: "$500–$3,000",
    windowText: "Open through Dec 31, 2026",
    sourceItemId: "africa-no-filter-kekere-storytellers-fund",
  },
  {
    title: "Frameline Completion Fund 2027",
    organization: "Frameline Completion Fund 2027",
    url: "https://www.frameline.org/artist-development/completion-fund",
    applicationUrl: "https://www.frameline.org/artist-development/completion-fund",
    category: "arts_film_media",
    eligibilityText: "Worldwide; LGBTQ+ films at least ~90% through production",
    focusText: "Film; documentary; narrative; experimental; animation; episodic",
    amountText: "$1,000–$5,000 standard grants",
    windowText: "Open Aug 31–Oct 9, 2026",
    sourceItemId: "frameline-completion-fund-2027",
  },
  {
    title: "Jewish Film Institute Grants 2027",
    organization: "Jewish Film Institute Grants 2027",
    url: "https://jfi.org/for-filmmakers/grants/application-guidelines",
    applicationUrl: "https://jfi.org/for-filmmakers/grants/application-guidelines",
    category: "arts_film_media",
    eligibilityText: "Worldwide; independent films/media exploring Jewish history, life, culture or identity; strong rough cut required",
    focusText: "Film; documentary; narrative; shorts; episodic/web series",
    amountText: "Completion funding; recent cycle awarded $95,000 across 6 projects",
    windowText: "Applications open Oct 2026; Phase 1 deadlines in Nov/Dec 2026",
    sourceItemId: "jewish-film-institute-grants-2027",
  },
  {
    title: "First Flights Short Film Fund",
    organization: "First Flights Short Film Fund",
    url: "https://www.first-flights.com/short-film-fund",
    applicationUrl: "https://www.first-flights.com/short-film-fund",
    category: "arts_film_media",
    eligibilityText: "Worldwide filmmakers; see project/rights rules",
    focusText: "Film; short film",
    amountText: "Up to £7,000 / approx. $10,000 + in-kind production awards",
    windowText: "Deadline: Oct 31, 2026",
    sourceItemId: "first-flights-short-film-fund",
  },
  {
    title: "Field of Vision — Documentary Commissions",
    organization: "Field of Vision",
    url: "https://fieldofvision.org/submit",
    applicationUrl: "https://fieldofvision.org/submit",
    category: "arts_film_media",
    eligibilityText: "Worldwide documentary filmmakers; editorial fit required",
    focusText: "Documentary film; nonfiction media",
    amountText: "Production funding; varies by commission",
    windowText: "Rolling",
    sourceItemId: "field-of-vision-documentary-commissions",
  },
  {
    title: "Pulitzer Center — Global Reporting Grants",
    organization: "Pulitzer Center",
    url: "https://pulitzercenter.org/grants-fellowships",
    applicationUrl: "https://pulitzercenter.org/grants-fellowships",
    category: "arts_film_media",
    eligibilityText: "Worldwide journalists and storytellers; eligibility varies by project",
    focusText: "Photography; documentary video; audio; multimedia storytelling",
    amountText: "Often $5,000–$10,000; varies",
    windowText: "Rolling",
    sourceItemId: "pulitzer-center-global-reporting-grants",
  },
  {
    title: "Festival de Cannes — La Résidence",
    organization: "Festival de Cannes",
    url: "https://www.festival-cannes.com/en/take-part/la-residence/",
    applicationUrl: "https://www.festival-cannes.com/en/take-part/la-residence/",
    category: "arts_film_media",
    eligibilityText: "Emerging filmmakers/directors; international eligibility, excluding certain France-based applicants",
    focusText: "Film; screenwriting/directing",
    amountText: "Paris residency support; one €5,000 CNC grant per session",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "festival-de-cannes-la-residence",
  },
  {
    title: "Script Pipeline First Look Project",
    organization: "Script Pipeline First Look Project",
    url: "https://scriptpipeline.com/first-look-project",
    applicationUrl: "https://scriptpipeline.com/first-look-project",
    category: "arts_film_media",
    eligibilityText: "Worldwide writers/filmmakers",
    focusText: "Screenwriting; film; television pilots",
    amountText: "$15,000 total across six winners",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "script-pipeline-first-look-project",
  },
  {
    title: "Basel House of Film — Filmmakers Residency",
    organization: "Basel House of Film",
    url: "https://www.baselfilm.ch/",
    applicationUrl: "https://www.baselfilm.ch/",
    category: "arts_film_media",
    eligibilityText: "International filmmakers; residency in Basel region, Switzerland",
    focusText: "Film; directing; screenwriting; development",
    amountText: "Housing + travel/living support; varies",
    windowText: "Rolling",
    sourceItemId: "basel-house-of-film-filmmakers-residency",
  },
  {
    title: "European Media Art Festival — Awards / Media Art Call",
    organization: "European Media Art Festival",
    url: "https://www.emaf.de/",
    applicationUrl: "https://www.emaf.de/",
    category: "arts_film_media",
    eligibilityText: "International media artists/filmmakers",
    focusText: "Film; video; media art; installation",
    amountText: "Selected works receive screening/production support; awards vary",
    windowText: "Deadline: Dec 15, 2026",
    sourceItemId: "european-media-art-festival-awards-media-art-call",
  },
  {
    title: "Vermont Studio Center — Artist & Writer Fellowships",
    organization: "Vermont Studio Center",
    url: "https://vermontstudiocenter.org/fellowships",
    applicationUrl: "https://vermontstudiocenter.org/fellowships",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide artists and writers",
    focusText: "Visual art; photography; writing; interdisciplinary",
    amountText: "Full/partial fellowship support for 2–4 week residencies",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "vermont-studio-center-artist-writer-fellowships",
  },
  {
    title: "Tony Elumelu Foundation Entrepreneurship Programme",
    organization: "Tony Elumelu Foundation Entrepreneurship Programme",
    url: "https://www.tonyelumelufoundation.org/",
    applicationUrl: "https://www.tonyelumelufoundation.org/",
    category: "business_creative_entrepreneur",
    eligibilityText: "Africa; start-ups 0–3 years old, founders 18+, nationals of an African country",
    focusText: "Any sector, including creative and community-focused businesses",
    amountText: "$5,000 non-refundable seed capital + training and mentorship",
    windowText: "2026 window closed (Jan 1–Mar 1, 2026); next cycle expected to open Jan 2027",
    sourceItemId: "tony-elumelu-foundation-entrepreneurship-programme",
  },
  {
    title: "Shell LiveWIRE",
    organization: "Shell LiveWIRE",
    url: "https://www.shell-livewire.org/",
    applicationUrl: "https://www.shell-livewire.org/",
    category: "business_creative_entrepreneur",
    eligibilityText: "Multiple countries incl. UK, South Africa and Malaysia; entrepreneurs aged 16–30",
    focusText: "Any small or growing business",
    amountText: "£5,000 monthly award; £25,000 annual award",
    windowText: "Rolling; monthly Smarter Future Awards plus an annual Young Entrepreneur of the Year award",
    sourceItemId: "shell-livewire",
  },
  {
    title: "Global Innovation Fund (GIF)",
    organization: "Global Innovation Fund (GIF)",
    url: "https://www.globalinnovation.fund/apply-for-funding",
    applicationUrl: "https://www.globalinnovation.fund/apply-for-funding",
    category: "business_creative_entrepreneur",
    eligibilityText: "Worldwide; social enterprises, nonprofits and businesses serving people living on under $5/day",
    focusText: "Social enterprise; livelihoods; financial health; climate resilience",
    amountText: "$50,000–$15,000,000 depending on stage",
    windowText: "Rolling; no fixed deadline",
    sourceItemId: "global-innovation-fund-gif",
  },
  {
    title: "Microsoft Nonprofit Technology Grants & Credits (incl. AI for Good)",
    organization: "Microsoft Nonprofit Technology Grants & Credits (incl. AI for Good)",
    url: "https://www.microsoft.com/en-us/nonprofits/offers-for-nonprofits",
    applicationUrl: "https://www.microsoft.com/en-us/nonprofits/offers-for-nonprofits",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide 501(c)(3)-equivalent nonprofits verified via TechSoup",
    focusText: "Nonprofit technology, AI, accessibility and digital-skills projects",
    amountText: "Software/cloud donations plus select cash grants, typically $50,000–$500,000 for AI for Good awards",
    windowText: "Rolling",
    sourceItemId: "microsoft-nonprofit-technology-grants-credits-incl-ai-for-good",
  },
  {
    title: "TechSoup Technology Donations & Grants Hub",
    organization: "TechSoup Technology Donations & Grants Hub",
    url: "https://www.techsoup.org/",
    applicationUrl: "https://www.techsoup.org/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide verified nonprofits, charities and libraries",
    focusText: "Nonprofit technology infrastructure and software",
    amountText: "Discounted/donated software, hardware and cloud credits",
    windowText: "Rolling",
    sourceItemId: "techsoup-technology-donations-grants-hub",
  },
  {
    title: "Mozilla Technology Fund",
    organization: "Mozilla Technology Fund",
    url: "https://www.mozillafoundation.org/en/what-we-fund/",
    applicationUrl: "https://www.mozillafoundation.org/en/what-we-fund/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide open-source project teams",
    focusText: "Open-source technology; internet health; AI auditing and transparency tools",
    amountText: "Up to $50,000 + 12-month mentorship cohort",
    windowText: "Rolling themed open calls; check site for the current call",
    sourceItemId: "mozilla-technology-fund",
  },
  {
    title: "GitHub Secure Open Source Fund",
    organization: "GitHub Secure Open Source Fund",
    url: "https://github.com/open-source/github-secure-open-source-fund",
    applicationUrl: "https://github.com/open-source/github-secure-open-source-fund",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide open-source maintainers (individuals or teams of up to 3) with an active GitHub profile",
    focusText: "Open-source project security improvements",
    amountText: "Funding tied to completed security work; amount varies by session",
    windowText: "Rolling, applications open continuously and considered for all upcoming program sessions",
    sourceItemId: "github-secure-open-source-fund",
  },
  {
    title: "Patrick J. McGovern Foundation — AI Fluency & Capacity Building Grants",
    organization: "Patrick J. McGovern Foundation",
    url: "https://www.mcgovern.org/grants/",
    applicationUrl: "https://www.mcgovern.org/grants/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide nonprofits and public institutions with existing data assets",
    focusText: "AI literacy; responsible AI deployment; data capacity building",
    amountText: "Varies",
    windowText: "Rolling (a recent cycle deadline was Jul 1, 2026); check site for the next window",
    sourceItemId: "patrick-j-mcgovern-foundation-ai-fluency-capacity-building-grants",
  },
];
