/**
 * Curated grants/fellowships/funding dataset.
 *
 * Unlike the job sources in src/lib/sources/ (which hit a live public API
 * per source), most grant-making organizations don't expose one — this
 * data is manually researched (from provided links + targeted web
 * research) and kept here as a single "source" the ingestion pipeline can
 * fetch from like any other. When new opportunities are found, add a new
 * RawGrant entry to CURATED_GRANTS below and re-run `npm run ingest:grants`
 * (or restart the dev server, which reads this same fallback data when
 * Supabase isn't configured yet).
 *
 * windowText is kept verbatim from the source — opensAt/deadline/isRolling
 * are BEST-EFFORT parses of it (see lib/grants/parse-window.ts), so the
 * original text is always shown to the user even when parsing can't
 * produce a precise date.
 *
 * Generated from the researched grants list on 2026-09-27. Do not hand-edit
 * the generated entries below this notice without also checking
 * parse-window.ts still handles their windowText format.
 */

import type { RawGrant } from "@/lib/grants/source-types";

export const CURATED_GRANTS: RawGrant[] = [
  {
    title: "Amphion Foundation Grant Program",
    organization: "Amphion Foundation Grant Program",
    url: "https://amphionfoundation.org/grant-program/",
    applicationUrl: "https://amphionfoundation.org/grant-program/",
    category: "arts_music",
    eligibilityText: "U.S.; nonprofit performing ensembles, presenters and music service organizations",
    focusText: "Music; contemporary concert music",
    amountText: "Typically $1,500–$7,500",
    windowText: "Deadline: Sep 24, 2026",
    sourceItemId: "amphion-foundation-grant-program",
  },
  {
    title: "GRAMMY Museum Grant Program — Scientific Research",
    organization: "GRAMMY Museum Grant Program",
    url: "https://grammymuseum.org/education/grants-program/",
    applicationUrl: "https://grammymuseum.org/education/grants-program/",
    category: "arts_music",
    eligibilityText: "U.S./North America; individuals and organizations conducting music-related research",
    focusText: "Music research; recorded sound",
    amountText: "Up to $20,000",
    windowText: "LOI deadline: Sep 25, 2026",
    sourceItemId: "grammy-museum-grant-program-scientific-research",
  },
  {
    title: "GRAMMY Museum Grant Program — Preservation Implementation",
    organization: "GRAMMY Museum Grant Program",
    url: "https://grammymuseum.org/education/grants-program/",
    applicationUrl: "https://grammymuseum.org/education/grants-program/",
    category: "arts_music",
    eligibilityText: "North America; organizations/institutional departments preserving recorded sound",
    focusText: "Music; archives; recorded-sound preservation",
    amountText: "Up to $20,000",
    windowText: "LOI deadline: Sep 25, 2026",
    sourceItemId: "grammy-museum-grant-program-preservation-implementation",
  },
  {
    title: "GRAMMY Museum Grant Program — Preservation Assistance",
    organization: "GRAMMY Museum Grant Program",
    url: "https://grammymuseum.org/education/grants-program/",
    applicationUrl: "https://grammymuseum.org/education/grants-program/",
    category: "arts_music",
    eligibilityText: "North America; individuals and small/mid-sized organizations",
    focusText: "Music; archives; recorded-sound preservation",
    amountText: "Up to $5,000",
    windowText: "LOI deadline: Sep 25, 2026",
    sourceItemId: "grammy-museum-grant-program-preservation-assistance",
  },
  {
    title: "South Arts Emerging Traditional Artists Program",
    organization: "South Arts Emerging Traditional Artists Program",
    url: "https://www.southarts.org/grants-opportunities/emerging-traditional-artists-program",
    applicationUrl: "https://www.southarts.org/grants-opportunities/emerging-traditional-artists-program",
    category: "arts_multidisciplinary",
    eligibilityText: "Eligible ARC/DRA counties in the South or members of state/federally recognized Native tribes",
    focusText: "Traditional music; folk arts; storytelling; craft; foodways",
    amountText: "$5,000",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "south-arts-emerging-traditional-artists-program",
  },
  {
    title: "Society for American Music — Hampsong Education Fellowship in American Song",
    organization: "Society for American Music",
    url: "https://hampsongfoundation.org/project/hampsongeducation-fellowship-in-american-song/",
    applicationUrl: "https://hampsongfoundation.org/project/hampsongeducation-fellowship-in-american-song/",
    category: "arts_music",
    eligibilityText: "U.S./international educators, performers and scholars working with American song",
    focusText: "Music; performance; music education; humanities",
    amountText: "Up to $1,000",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "society-for-american-music-hampsong-education-fellowship-in-american-song",
  },
  {
    title: "Society for American Music — John Koegel Latin American & Latinx Music Fellowship",
    organization: "Society for American Music",
    url: "https://www.american-music.org/award-fellowship/latin-american-and-latinx-fellowship/",
    applicationUrl: "https://www.american-music.org/award-fellowship/latin-american-and-latinx-fellowship/",
    category: "arts_music",
    eligibilityText: "SAM members; research on Latin American/Latinx musical life",
    focusText: "Music; musicology; archival/ethnographic research",
    amountText: "Up to $2,000",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "society-for-american-music-john-koegel-latin-american-latinx-music-fellowship",
  },
  {
    title: "Wisconsin Arts Board — Creation and Presentation Program",
    organization: "Wisconsin Arts Board",
    url: "https://artsboard.wisconsin.gov/Pages/Community/CreationPresentation.aspx",
    applicationUrl: "https://artsboard.wisconsin.gov/Pages/Community/CreationPresentation.aspx",
    category: "arts_multidisciplinary",
    eligibilityText: "Wisconsin arts organizations and eligible applicants; public arts programming",
    focusText: "Music; performing arts; visual arts; multidisciplinary",
    amountText: "Varies by award",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "wisconsin-arts-board-creation-and-presentation-program",
  },
  {
    title: "Café Royal Cultural Foundation — Fall 2026 Music Production Grant",
    organization: "Café Royal Cultural Foundation",
    url: "https://caferoyalculturalfoundation.org/music-page",
    applicationUrl: "https://caferoyalculturalfoundation.org/music-page",
    category: "arts_music",
    eligibilityText: "Individual musicians; recording should take place in/near NYC or be pre-approved",
    focusText: "Music; audio recording; mixing; editing; mastering",
    amountText: "Up to $20,000",
    windowText: "Deadline: Nov 2, 2026, 9:00 a.m. ET or when 40 applications are received",
    sourceItemId: "cafe-royal-cultural-foundation-fall-2026-music-production-grant",
  },
  {
    title: "Café Royal Cultural Foundation — Fall 2026 Performance Grant",
    organization: "Café Royal Cultural Foundation",
    url: "https://caferoyalculturalfoundation.org/grant-schedule",
    applicationUrl: "https://caferoyalculturalfoundation.org/grant-schedule",
    category: "arts_theater_performance",
    eligibilityText: "Individual artists producing theater, dance or performance art; music may accompany work",
    focusText: "Performance; music; theater; dance",
    amountText: "Up to $10,000",
    windowText: "Deadline: Nov 2, 2026, 9:00 a.m. ET or when 40 applications are received",
    sourceItemId: "cafe-royal-cultural-foundation-fall-2026-performance-grant",
  },
  {
    title: "Alaska State Council on the Arts — Artists in Schools Grants",
    organization: "Alaska State Council on the Arts",
    url: "https://arts.alaska.gov/grants",
    applicationUrl: "https://arts.alaska.gov/grants",
    category: "arts_multidisciplinary",
    eligibilityText: "Alaska schools/organizations working with teaching artists",
    focusText: "Music; performing arts; visual arts; literary arts",
    amountText: "Varies",
    windowText: "Deadline: Nov 1, 2026",
    sourceItemId: "alaska-state-council-on-the-arts-artists-in-schools-grants",
  },
  {
    title: "Musicians Advocacy Fund — Fall 2026 Grant Round",
    organization: "Musicians Advocacy Fund",
    url: "https://musiciansadvocacyfund.org/",
    applicationUrl: "https://musiciansadvocacyfund.org/",
    category: "arts_music",
    eligibilityText: "U.S.; music-related charitable/educational projects and eligible artists/organizations",
    focusText: "Music; education; performance; community programs",
    amountText: "Varies",
    windowText: "Deadline: Oct 30, 2026",
    sourceItemId: "musicians-advocacy-fund-fall-2026-grant-round",
  },
  {
    title: "Aaron Copland Fund for Music — Project Support Main Round",
    organization: "Aaron Copland Fund for Music",
    url: "https://coplandfund.org/project-support",
    applicationUrl: "https://coplandfund.org/project-support",
    category: "arts_music",
    eligibilityText: "U.S.; eligible ensembles, presenters, organizations and recording projects",
    focusText: "American concert music; jazz; contemporary composition",
    amountText: "Varies",
    windowText: "Deadline: Nov 12, 2026",
    sourceItemId: "aaron-copland-fund-for-music-project-support-main-round",
  },
  {
    title: "Arkansas Arts Council — General Operating Support FY28",
    organization: "Arkansas Arts Council",
    url: "https://www.arkansasheritage.com/arkansas-art-council/aac-grants",
    applicationUrl: "https://www.arkansasheritage.com/arkansas-art-council/aac-grants",
    category: "arts_multidisciplinary",
    eligibilityText: "Arkansas eligible arts organizations",
    focusText: "Music; performing arts; visual arts; multidisciplinary",
    amountText: "Varies",
    windowText: "Deadline: Dec 3, 2026",
    sourceItemId: "arkansas-arts-council-general-operating-support-fy28",
  },
  {
    title: "Puffin Foundation — 2027 Artist Grant Cycle",
    organization: "Puffin Foundation",
    url: "https://www.puffinfoundation.org/grants-info/",
    applicationUrl: "https://www.puffinfoundation.org/grants-info/",
    category: "arts_multidisciplinary",
    eligibilityText: "U.S. residents with SSN and U.S.-based nonprofits",
    focusText: "Music; fine arts; photography; film/video; theater; artistic activism",
    amountText: "Up to $3,500",
    windowText: "Open Sep 14–Dec 16, 2026",
    sourceItemId: "puffin-foundation-2027-artist-grant-cycle",
  },
  {
    title: "Musicians Foundation — One-Time Financial Assistance",
    organization: "Musicians Foundation",
    url: "https://musiciansfoundation.org/apply/",
    applicationUrl: "https://musiciansfoundation.org/apply/",
    category: "arts_music",
    eligibilityText: "U.S.; professional musicians in financial need",
    focusText: "Music; professional musicians",
    amountText: "Need-based; varies",
    windowText: "Rolling",
    sourceItemId: "musicians-foundation-one-time-financial-assistance",
  },
  {
    title: "Sweet Relief Musicians Fund — Financial Assistance",
    organization: "Sweet Relief Musicians Fund",
    url: "https://www.sweetrelief.org/request-assistance.html",
    applicationUrl: "https://www.sweetrelief.org/request-assistance.html",
    category: "arts_music",
    eligibilityText: "U.S.; career musicians and music-industry workers facing illness, disability or age-related hardship",
    focusText: "Music; music industry",
    amountText: "Need-based; varies",
    windowText: "Rolling",
    sourceItemId: "sweet-relief-musicians-fund-financial-assistance",
  },
  {
    title: "Jazz Foundation of America — Musicians' Emergency Fund",
    organization: "Jazz Foundation of America",
    url: "https://jazzfoundation.org/musicians-emergency-fund/",
    applicationUrl: "https://jazzfoundation.org/musicians-emergency-fund/",
    category: "arts_music",
    eligibilityText: "U.S.; professional jazz, blues and roots musicians in crisis",
    focusText: "Music; jazz; blues; roots",
    amountText: "Need-based; varies",
    windowText: "Rolling",
    sourceItemId: "jazz-foundation-of-america-musicians-emergency-fund",
  },
  {
    title: "New Music USA — Reel Change Film Fund",
    organization: "New Music USA",
    url: "https://newmusicusa.org/program/reel-change-film-fund/",
    applicationUrl: "https://newmusicusa.org/program/reel-change-film-fund/",
    category: "arts_film_media",
    eligibilityText: "U.S.-based composers creating original music for film",
    focusText: "Music composition; film scoring",
    amountText: "Project funding; varies",
    windowText: "Rolling",
    sourceItemId: "new-music-usa-reel-change-film-fund",
  },
  {
    title: "Arkansas Arts Council — Sally A. Williams Artist Fund",
    organization: "Arkansas Arts Council",
    url: "https://www.arkansasheritage.com/arkansas-art-council/aac-grants",
    applicationUrl: "https://www.arkansasheritage.com/arkansas-art-council/aac-grants",
    category: "arts_multidisciplinary",
    eligibilityText: "Arkansas individual artists",
    focusText: "Music; visual arts; literary arts; performing arts",
    amountText: "Varies",
    windowText: "Rolling",
    sourceItemId: "arkansas-arts-council-sally-a-williams-artist-fund",
  },
  {
    title: "Colorado Artist Relief Fund",
    organization: "Colorado Artist Relief Fund",
    url: "https://www.redlineart.org/colorado-artist-relief-fund",
    applicationUrl: "https://www.redlineart.org/colorado-artist-relief-fund",
    category: "arts_multidisciplinary",
    eligibilityText: "Colorado artists experiencing emergency hardship",
    focusText: "Music; performing arts; visual arts; literary arts; film/media",
    amountText: "Emergency support; varies",
    windowText: "Rolling while funds are available",
    sourceItemId: "colorado-artist-relief-fund",
  },
  {
    title: "Alabama Humanities Alliance — Mini Grants",
    organization: "Alabama Humanities Alliance",
    url: "https://alabamahumanities.org/grants/",
    applicationUrl: "https://alabamahumanities.org/grants/",
    category: "arts_multidisciplinary",
    eligibilityText: "Alabama-based eligible organizations and community projects",
    focusText: "Music-related humanities; storytelling; film; culture",
    amountText: "Typically up to $3,000",
    windowText: "Monthly / rolling cycles",
    sourceItemId: "alabama-humanities-alliance-mini-grants",
  },
  {
    title: "Foundation for Contemporary Arts — Emergency Grants",
    organization: "Foundation for Contemporary Arts",
    url: "https://www.foundationforcontemporaryarts.org/grants/emergency-grants/",
    applicationUrl: "https://www.foundationforcontemporaryarts.org/grants/emergency-grants/",
    category: "arts_multidisciplinary",
    eligibilityText: "U.S.-based artists with urgent, unexpected project expenses",
    focusText: "Performance; dance; music/sound; theater; poetry; visual arts",
    amountText: "$500–$3,000",
    windowText: "Rolling",
    sourceItemId: "foundation-for-contemporary-arts-emergency-grants",
  },
  {
    title: "Awesome Foundation — Monthly Microgrants",
    organization: "Awesome Foundation",
    url: "https://www.awesomefoundation.org/en",
    applicationUrl: "https://www.awesomefoundation.org/en",
    category: "community_civic",
    eligibilityText: "Worldwide; eligibility varies by chapter",
    focusText: "Music; film; photography; visual art; community creative projects",
    amountText: "$1,000",
    windowText: "Rolling; chapters award monthly",
    sourceItemId: "awesome-foundation-monthly-microgrants",
  },
  {
    title: "Arts in Neighborhoods Community Event Mini-Grant — October Round",
    organization: "Arts in Neighborhoods Community Event Mini-Grant",
    url: "https://fundforthearts.org/",
    applicationUrl: "https://fundforthearts.org/",
    category: "arts_multidisciplinary",
    eligibilityText: "Greater Louisville, Kentucky; free public community events",
    focusText: "Music; performance; multidisciplinary arts",
    amountText: "$500–$5,000",
    windowText: "Deadline: Oct 16, 2026",
    sourceItemId: "arts-in-neighborhoods-community-event-mini-grant-october-round",
  },
  {
    title: "City & County of Broomfield — Arts, Culture and Science Grant",
    organization: "City & County of Broomfield",
    url: "https://www.broomfield.org/",
    applicationUrl: "https://www.broomfield.org/",
    category: "arts_multidisciplinary",
    eligibilityText: "Broomfield, Colorado; organizations, groups and fiscally sponsored individuals",
    focusText: "Music; arts; culture; science programming",
    amountText: "Up to $2,000",
    windowText: "Open through Oct 31, 2026 or until funds are exhausted",
    sourceItemId: "city-county-of-broomfield-arts-culture-and-science-grant",
  },
  {
    title: "Friends of IFCC Artist Grant & Residency Program",
    organization: "Friends of IFCC Artist Grant & Residency Program",
    url: "https://www.portland.gov/arts/grantmaking",
    applicationUrl: "https://www.portland.gov/arts/grantmaking",
    category: "arts_multidisciplinary",
    eligibilityText: "Portland, Oregon; individual artists",
    focusText: "Music; film/media; visual arts; performance; multidisciplinary",
    amountText: "$1,000–$5,000",
    windowText: "Open Aug 31–Oct 16, 2026",
    sourceItemId: "friends-of-ifcc-artist-grant-residency-program",
  },
  {
    title: "RACC Portland Arts Project Grants",
    organization: "RACC Portland Arts Project Grants",
    url: "https://www.portland.gov/arts/grantmaking",
    applicationUrl: "https://www.portland.gov/arts/grantmaking",
    category: "arts_multidisciplinary",
    eligibilityText: "Portland, Oregon; individual artists, collectives, arts businesses, schools and nonprofits",
    focusText: "Music; film/media; visual art; performance; multidisciplinary",
    amountText: "$1,000–$5,000",
    windowText: "Open Sep 1–Oct 28, 2026",
    sourceItemId: "racc-portland-arts-project-grants",
  },
  {
    title: "Mass Cultural Council — Grants for Creative Individuals",
    organization: "Mass Cultural Council",
    url: "https://massculturalcouncil.org/programs-at-a-glance/",
    applicationUrl: "https://massculturalcouncil.org/programs-at-a-glance/",
    category: "arts_multidisciplinary",
    eligibilityText: "Massachusetts artists, culture bearers and creative individuals",
    focusText: "Music; film; photography; visual and performing arts; multidisciplinary",
    amountText: "$5,000 unrestricted",
    windowText: "Open Sep 10–Oct 27, 2026",
    sourceItemId: "mass-cultural-council-grants-for-creative-individuals",
  },
  {
    title: "Mass Cultural Council — Local Cultural Council Grants",
    organization: "Mass Cultural Council",
    url: "https://massculturalcouncil.org/communities/local-cultural-council-program/application-process/",
    applicationUrl: "https://massculturalcouncil.org/communities/local-cultural-council-program/application-process/",
    category: "arts_multidisciplinary",
    eligibilityText: "Massachusetts; individuals, groups and organizations applying to a local council",
    focusText: "Music; film; photography; visual art; performance; humanities",
    amountText: "Varies; average awards often $500–$750",
    windowText: "Open Sep 1–Oct 15, 2026",
    sourceItemId: "mass-cultural-council-local-cultural-council-grants",
  },
  {
    title: "Mass Cultural Council — Tribal Cultural Council Grants",
    organization: "Mass Cultural Council",
    url: "https://massculturalcouncil.org/communities/tribal-cultural-council-program/application-process/",
    applicationUrl: "https://massculturalcouncil.org/communities/tribal-cultural-council-program/application-process/",
    category: "arts_multidisciplinary",
    eligibilityText: "Eligible Native/Indigenous communities served by participating Massachusetts Tribal Cultural Councils",
    focusText: "Music; film; photography; visual art; public programs; fellowships",
    amountText: "Varies",
    windowText: "Open Sep 1–Oct 15, 2026",
    sourceItemId: "mass-cultural-council-tribal-cultural-council-grants",
  },
  {
    title: "Los Angeles DCA — Neighborhood Engagement Artist Residency (NEAR)",
    organization: "Los Angeles DCA",
    url: "https://culture.lacity.gov/grants/near-co-op",
    applicationUrl: "https://culture.lacity.gov/grants/near-co-op",
    category: "arts_multidisciplinary",
    eligibilityText: "City of Los Angeles; independent artists proposing participatory residencies in non-arts venues",
    focusText: "Music; film/media; visual art; performance; multidisciplinary",
    amountText: "$12,000",
    windowText: "Deadline: Oct 30, 2026",
    sourceItemId: "los-angeles-dca-neighborhood-engagement-artist-residency-near",
  },
  {
    title: "Los Angeles DCA — Creative Optimism-Uplifting Promises (CO-UP)",
    organization: "Los Angeles DCA",
    url: "https://culture.lacity.gov/grants/near-co-op",
    applicationUrl: "https://culture.lacity.gov/grants/near-co-op",
    category: "arts_multidisciplinary",
    eligibilityText: "City of Los Angeles; independent artists proposing community-based participatory projects",
    focusText: "Music; film/media; visual art; performance; multidisciplinary",
    amountText: "$15,000",
    windowText: "Deadline: Oct 30, 2026",
    sourceItemId: "los-angeles-dca-creative-optimism-uplifting-promises-co-up",
  },
  {
    title: "Arizona Commission on the Arts — Artist Opportunity Grant, Cycle B",
    organization: "Arizona Commission on the Arts",
    url: "https://azarts.gov/grant/artist-opportunity/",
    applicationUrl: "https://azarts.gov/grant/artist-opportunity/",
    category: "arts_multidisciplinary",
    eligibilityText: "Arizona individual artists",
    focusText: "All artistic disciplines, including music, film/media, photography and visual art",
    amountText: "Up to $1,500",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "arizona-commission-on-the-arts-artist-opportunity-grant-cycle-b",
  },
  {
    title: "Illinois Arts Council — Creative Accelerator Fund",
    organization: "Illinois Arts Council",
    url: "https://arts.illinois.gov/",
    applicationUrl: "https://arts.illinois.gov/",
    category: "arts_multidisciplinary",
    eligibilityText: "Illinois individual artists",
    focusText: "All disciplines, including music, film/media, photography and visual art",
    amountText: "$10,000 unrestricted",
    windowText: "Deadline: Oct 14, 2026",
    sourceItemId: "illinois-arts-council-creative-accelerator-fund",
  },
  {
    title: "Mid-America Arts Alliance — Catalyze",
    organization: "Mid-America Arts Alliance",
    url: "https://www.maaa.org/programs-grants/for-artists/catalyze/",
    applicationUrl: "https://www.maaa.org/programs-grants/for-artists/catalyze/",
    category: "arts_multidisciplinary",
    eligibilityText: "Individual artists in eligible M-AAA region; see current guidelines",
    focusText: "All disciplines, including music, film/media, photography and visual art",
    amountText: "$10,000",
    windowText: "Open Oct 1–Dec 1, 2026",
    sourceItemId: "mid-america-arts-alliance-catalyze",
  },
  {
    title: "NC Artist Support Grant — Region 14",
    organization: "NC Artist Support Grant",
    url: "https://www.burkearts.org/artist-grants-2026",
    applicationUrl: "https://www.burkearts.org/artist-grants-2026",
    category: "arts_multidisciplinary",
    eligibilityText: "Alexander, Burke, Caldwell, Catawba, Iredell and McDowell counties, North Carolina",
    focusText: "Music; photography; visual art; craft; theater; literary arts",
    amountText: "$500–$1,500",
    windowText: "Open Sep 1–Sep 30, 2026",
    sourceItemId: "nc-artist-support-grant-region-14",
  },
  {
    title: "NC Artist Support Grant — Arts of the Albemarle Region",
    organization: "NC Artist Support Grant",
    url: "https://www.artsaoa.org/artist-support-grant",
    applicationUrl: "https://www.artsaoa.org/artist-support-grant",
    category: "arts_multidisciplinary",
    eligibilityText: "Bertie, Camden, Chowan, Currituck, Gates, Hertford, Pasquotank and Perquimans counties, NC",
    focusText: "Music; photography; visual art; film/media; all disciplines",
    amountText: "$500–$1,000",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "nc-artist-support-grant-arts-of-the-albemarle-region",
  },
  {
    title: "NC Artist Support Grant — Region 12 / Arts Council of Moore County",
    organization: "NC Artist Support Grant",
    url: "https://www.mooreart.org/grants-and-scholarships/artist-support-grant/",
    applicationUrl: "https://www.mooreart.org/grants-and-scholarships/artist-support-grant/",
    category: "arts_multidisciplinary",
    eligibilityText: "Anson, Montgomery, Moore, Richmond, Stanly and Union counties, North Carolina",
    focusText: "Music; photography; visual art; film/media; all disciplines",
    amountText: "Varies; recent awards approx. $1,500–$2,500",
    windowText: "Deadline: Oct 9, 2026",
    sourceItemId: "nc-artist-support-grant-region-12-arts-council-of-moore-county",
  },
  {
    title: "Huntington Arts Council — Bi-Monthly Community Impact Micro Grant",
    organization: "Huntington Arts Council",
    url: "https://form.jotform.com/251754373770159",
    applicationUrl: "https://form.jotform.com/251754373770159",
    category: "arts_multidisciplinary",
    eligibilityText: "Nassau & Suffolk counties, New York; individual artists, groups and nonprofits",
    focusText: "Music; media arts; visual arts; performing arts; literary arts",
    amountText: "$1,000",
    windowText: "Next deadline: Nov 6, 2026",
    sourceItemId: "huntington-arts-council-bi-monthly-community-impact-micro-grant",
  },
  {
    title: "Southern Finger Lakes Artist Fellowship — 2027 Cycle",
    organization: "Southern Finger Lakes Artist Fellowship",
    url: "https://www.earts.org/southern-finger-lakes-artist-fellowship/",
    applicationUrl: "https://www.earts.org/southern-finger-lakes-artist-fellowship/",
    category: "arts_multidisciplinary",
    eligibilityText: "Cattaraugus, Chemung, Schuyler, Steuben and Tioga counties, New York",
    focusText: "All artistic disciplines",
    amountText: "Unrestricted cash award; amount announced with cycle",
    windowText: "Opens Nov 2026",
    sourceItemId: "southern-finger-lakes-artist-fellowship-2027-cycle",
  },
  {
    title: "Willie Stoffer Grant — Inglewood Open Studios",
    organization: "Willie Stoffer Grant",
    url: "https://inglewoodopenstudios.org/grantopportunity",
    applicationUrl: "https://inglewoodopenstudios.org/grantopportunity",
    category: "arts_visual_photography",
    eligibilityText: "Inglewood, California; I.O.S. member artists; membership can be added with application",
    focusText: "Visual art; photography; multidisciplinary",
    amountText: "$1,800",
    windowText: "Deadline: Oct 25, 2026",
    sourceItemId: "willie-stoffer-grant-inglewood-open-studios",
  },
  {
    title: "Santa Monica Individual Artist Project Grants",
    organization: "Santa Monica Individual Artist Project Grants",
    url: "https://www.santamonica.gov/categories/programs/arts-and-culture",
    applicationUrl: "https://www.santamonica.gov/categories/programs/arts-and-culture",
    category: "arts_multidisciplinary",
    eligibilityText: "Santa Monica, California individual artists",
    focusText: "Music; film; photography; visual arts; literary and performing arts",
    amountText: "Project support; varies",
    windowText: "Deadline: Sep 29, 2026",
    sourceItemId: "santa-monica-individual-artist-project-grants",
  },
  {
    title: "Amplify Arts — 2027 Fellowship",
    organization: "Amplify Arts",
    url: "https://www.amplifyarts.org/",
    applicationUrl: "https://www.amplifyarts.org/",
    category: "arts_multidisciplinary",
    eligibilityText: "Greater Omaha–Council Bluffs metro artists",
    focusText: "Film; performance; visual art; public/site-responsive work; multidisciplinary",
    amountText: "$10,000 project support",
    windowText: "Deadline: Oct 4, 2026",
    sourceItemId: "amplify-arts-2027-fellowship",
  },
  {
    title: "AAPI Civic Engagement Fund — 2027 Creative Catalyst Fellowship",
    organization: "AAPI Civic Engagement Fund",
    url: "https://aapifund.org/2027-creative-catalyst-fellowship-open-call/",
    applicationUrl: "https://aapifund.org/2027-creative-catalyst-fellowship-open-call/",
    category: "arts_multidisciplinary",
    eligibilityText: "U.S.-based individual artists engaging AAPI communities; see full eligibility",
    focusText: "Music/hip-hop; documentary; animation; visual art; writing; interdisciplinary",
    amountText: "$30,000",
    windowText: "Deadline: Oct 15, 2026, 11:59 p.m. PT",
    sourceItemId: "aapi-civic-engagement-fund-2027-creative-catalyst-fellowship",
  },
  {
    title: "The Supporting Act Foundation — 2026 Artist Grant",
    organization: "The Supporting Act Foundation",
    url: "https://thesupportingact.org/programs/artist-grant/2026",
    applicationUrl: "https://thesupportingact.org/programs/artist-grant/2026",
    category: "arts_multidisciplinary",
    eligibilityText: "Artists based in Belgium, France, Germany, Greece, Ireland, Italy, Netherlands, Portugal, Spain or UK",
    focusText: "Music; visual art; performance; multidisciplinary",
    amountText: "€10,000 unrestricted",
    windowText: "Deadline: Oct 1, 2026, 11:00 a.m. CET",
    sourceItemId: "the-supporting-act-foundation-2026-artist-grant",
  },
  {
    title: "Creative Australia — Music Australia Export Development Fund, Category 2",
    organization: "Creative Australia",
    url: "https://creative.gov.au/investment-and-development/music-australia/",
    applicationUrl: "https://creative.gov.au/investment-and-development/music-australia/",
    category: "arts_music",
    eligibilityText: "Australia; eligible music artists and industry applicants",
    focusText: "Music; international professional/artistic development",
    amountText: "Up to AUD $15,000 matched funding",
    windowText: "Deadline: Oct 13, 2026",
    sourceItemId: "creative-australia-music-australia-export-development-fund-category-2",
  },
  {
    title: "Creative Australia — International Engagement Fund",
    organization: "Creative Australia",
    url: "https://creative.gov.au/investment-and-development/",
    applicationUrl: "https://creative.gov.au/investment-and-development/",
    category: "arts_multidisciplinary",
    eligibilityText: "Australia; eligible artists/organizations with confirmed international partners",
    focusText: "Music; visual art; performing arts; cross-disciplinary",
    amountText: "AUD $5,000–$30,000",
    windowText: "Deadline: Oct 13, 2026",
    sourceItemId: "creative-australia-international-engagement-fund",
  },
  {
    title: "NORMA Fonds — Performing Artists Project Support",
    organization: "NORMA Fonds",
    url: "https://www.normafonds.nl/",
    applicationUrl: "https://www.normafonds.nl/",
    category: "arts_theater_performance",
    eligibilityText: "Netherlands; eligible individual performing artists and organizations",
    focusText: "Music; dance; acting; voice/performance",
    amountText: "Up to €10,000",
    windowText: "Open Oct 1–Oct 30, 2026",
    sourceItemId: "norma-fonds-performing-artists-project-support",
  },
  {
    title: "Arts Council England — Music Creators Growth Fund",
    organization: "Arts Council England",
    url: "https://www.artscouncil.org.uk/",
    applicationUrl: "https://www.artscouncil.org.uk/",
    category: "arts_music",
    eligibilityText: "England; experienced artists and music creators",
    focusText: "Music; career development; touring; international activity",
    amountText: "£10,000–£20,000",
    windowText: "Opens Oct 1, 2026",
    sourceItemId: "arts-council-england-music-creators-growth-fund",
  },
  {
    title: "Arts Council England — Music Growth Fund",
    organization: "Arts Council England",
    url: "https://www.artscouncil.org.uk/",
    applicationUrl: "https://www.artscouncil.org.uk/",
    category: "arts_music",
    eligibilityText: "England; eligible music organizations/businesses",
    focusText: "Music sector growth and development",
    amountText: "£1,000–£40,000",
    windowText: "Round closes Oct 15, 2026; next round closes Nov 26, 2026",
    sourceItemId: "arts-council-england-music-growth-fund",
  },
  {
    title: "Artist Grant — November 2026",
    organization: "Artist Grant",
    url: "https://artistgrant.org/apply",
    applicationUrl: "https://artistgrant.org/apply",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; visual artists age 18+",
    focusText: "Photography; painting; drawing; sculpture; ceramics; printmaking; mixed media",
    amountText: "$1,200 unrestricted",
    windowText: "Deadline: Nov 15, 2026",
    sourceItemId: "artist-grant-november-2026",
  },
  {
    title: "The Hopper Prize — Fall 2026",
    organization: "The Hopper Prize",
    url: "https://hopperprize.org/",
    applicationUrl: "https://hopperprize.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "Photography; visual art; mixed media; any medium",
    amountText: "2 × $4,500 + 4 × $1,000",
    windowText: "Deadline: Nov 17, 2026",
    sourceItemId: "the-hopper-prize-fall-2026",
  },
  {
    title: "Pollock-Krasner Foundation Grant",
    organization: "Pollock-Krasner Foundation Grant",
    url: "https://pkf.org/apply/",
    applicationUrl: "https://pkf.org/apply/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; professional painters, sculptors and artists working on paper",
    focusText: "Painting; sculpture; works on paper",
    amountText: "Up to $50,000",
    windowText: "Rolling",
    sourceItemId: "pollock-krasner-foundation-grant",
  },
  {
    title: "Adolph & Esther Gottlieb Foundation — Emergency Grant",
    organization: "Adolph & Esther Gottlieb Foundation",
    url: "https://www.gottliebfoundation.org/emergency-grant",
    applicationUrl: "https://www.gottliebfoundation.org/emergency-grant",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; mature visual artists facing a one-time catastrophic emergency",
    focusText: "Painting; sculpture; printmaking",
    amountText: "Typically up to $15,000",
    windowText: "Rolling",
    sourceItemId: "adolph-esther-gottlieb-foundation-emergency-grant",
  },
  {
    title: "Artists' Fellowship — Emergency Financial Aid",
    organization: "Artists' Fellowship",
    url: "https://artistsfellowship.org/",
    applicationUrl: "https://artistsfellowship.org/",
    category: "arts_visual_photography",
    eligibilityText: "U.S.; professional fine artists in need because of illness, disaster or bereavement",
    focusText: "Fine art; visual art",
    amountText: "Need-based; varies",
    windowText: "Rolling",
    sourceItemId: "artists-fellowship-emergency-financial-aid",
  },
  {
    title: "CERF+ Emergency Relief Grant",
    organization: "CERF+ Emergency Relief Grant",
    url: "https://cerfplus.org/get-relief/apply-for-help/",
    applicationUrl: "https://cerfplus.org/get-relief/apply-for-help/",
    category: "arts_visual_photography",
    eligibilityText: "U.S.; eligible professional craft artists after a recent emergency",
    focusText: "Craft; visual art",
    amountText: "$3,000",
    windowText: "Reopens Oct 1, 2026; rolling thereafter",
    sourceItemId: "cerf-emergency-relief-grant",
  },
  {
    title: "ArtFundMe — Autumn 2026 Artist Grant",
    organization: "ArtFundMe",
    url: "https://artfundme.org/",
    applicationUrl: "https://artfundme.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "Visual art; photography; film; sound; mixed media; multidisciplinary",
    amountText: "$1,000",
    windowText: "Open Sep 18–Nov 20, 2026",
    sourceItemId: "artfundme-autumn-2026-artist-grant",
  },
  {
    title: "Artadia Houston Awards",
    organization: "Artadia Houston Awards",
    url: "https://artadia.org/awards",
    applicationUrl: "https://artadia.org/awards",
    category: "arts_visual_photography",
    eligibilityText: "Houston-area contemporary visual artists meeting residency rules",
    focusText: "Visual art; photography; new media; interdisciplinary visual practice",
    amountText: "$15,000 unrestricted",
    windowText: "Open Oct 1–Nov 1, 2026",
    sourceItemId: "artadia-houston-awards",
  },
  {
    title: ".ART Award 2026",
    organization: ".ART Award 2026",
    url: "https://art.art/award/",
    applicationUrl: "https://art.art/award/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; artists 18+",
    focusText: "All visual/media disciplines",
    amountText: "Grand prize includes $15,000 cash; $50,000+ total prize value",
    windowText: "Deadline: Nov 1, 2026",
    sourceItemId: "art-award-2026",
  },
  {
    title: "PhMuseum Women Photographers Grant 2026",
    organization: "PhMuseum Women Photographers Grant 2026",
    url: "https://phmuseum.com/grants",
    applicationUrl: "https://phmuseum.com/grants",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide; women and nonbinary photographers",
    focusText: "Photography",
    amountText: "€10,000 total cash grants + additional opportunities",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "phmuseum-women-photographers-grant-2026",
  },
  {
    title: "Gomma Photography Grant 2026",
    organization: "Gomma Photography Grant 2026",
    url: "https://www.gommagrant.com/",
    applicationUrl: "https://www.gommagrant.com/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide photographers",
    focusText: "Photography",
    amountText: "Top cash prize €1,000 + additional awards",
    windowText: "Final deadline: Nov 5, 2026",
    sourceItemId: "gomma-photography-grant-2026",
  },
  {
    title: "eidolon Grant 2026",
    organization: "eidolon Grant 2026",
    url: "https://www.eidoloncentre.org/",
    applicationUrl: "https://www.eidoloncentre.org/",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide",
    focusText: "Photography; vernacular/found photography research and artistic practice",
    amountText: "€25,000 total across categories",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "eidolon-grant-2026",
  },
  {
    title: "Phenomenon Grant 2026",
    organization: "Phenomenon Grant 2026",
    url: "https://phenomenon.gr/",
    applicationUrl: "https://phenomenon.gr/",
    category: "arts_visual_photography",
    eligibilityText: "Projects rooted in Greece; individual/collective eligibility varies by track",
    focusText: "Visual art; research-driven art; interdisciplinary",
    amountText: "€5,000–€10,000",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "phenomenon-grant-2026",
  },
  {
    title: "Waag Futurelab — Trust Me, I'm an AI/rtist",
    organization: "Waag Futurelab",
    url: "https://waag.org/",
    applicationUrl: "https://waag.org/",
    category: "arts_visual_photography",
    eligibilityText: "Europe; eligible creatives able to invoice/VAT as required",
    focusText: "Digital art; sound; performance; AI/new media",
    amountText: "€20,000 commission incl. project costs",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "waag-futurelab-trust-me-i-m-an-ai-rtist",
  },
  {
    title: "Lighthouse Works Fellowship",
    organization: "Lighthouse Works Fellowship",
    url: "https://www.thelighthouseworks.com/fellowship",
    applicationUrl: "https://www.thelighthouseworks.com/fellowship",
    category: "arts_visual_photography",
    eligibilityText: "Primarily U.S.-based artists; residency on Fishers Island, NY",
    focusText: "Visual art; photography; film/video; new media; writing",
    amountText: "$1,750 stipend + housing/food/studio",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "lighthouse-works-fellowship",
  },
  {
    title: "Oklahoma Visual Arts Coalition — Creative Projects Grant",
    organization: "Oklahoma Visual Arts Coalition",
    url: "https://ovac-ok.org/artist-grants/",
    applicationUrl: "https://ovac-ok.org/artist-grants/",
    category: "arts_visual_photography",
    eligibilityText: "Oklahoma visual artists",
    focusText: "Photography; visual art; new media; craft",
    amountText: "Up to $1,500",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "oklahoma-visual-arts-coalition-creative-projects-grant",
  },
  {
    title: "Oklahoma Visual Arts Coalition — Education Assistance Grant",
    organization: "Oklahoma Visual Arts Coalition",
    url: "https://ovac-ok.org/artist-grants/",
    applicationUrl: "https://ovac-ok.org/artist-grants/",
    category: "arts_visual_photography",
    eligibilityText: "Oklahoma visual artists",
    focusText: "Photography; visual art; professional development",
    amountText: "Varies; see current guidelines",
    windowText: "Deadline: Oct 15, 2026",
    sourceItemId: "oklahoma-visual-arts-coalition-education-assistance-grant",
  },
  {
    title: "Ontario Arts Council — Visual Artists Creation Projects",
    organization: "Ontario Arts Council",
    url: "https://www.arts.on.ca/grants/visual-artists-creation-projects",
    applicationUrl: "https://www.arts.on.ca/grants/visual-artists-creation-projects",
    category: "arts_visual_photography",
    eligibilityText: "Ontario, Canada resident visual artists",
    focusText: "Photography; visual art; media art",
    amountText: "CAD $5,000–$15,000",
    windowText: "Deadline: Nov 3, 2026",
    sourceItemId: "ontario-arts-council-visual-artists-creation-projects",
  },
  {
    title: "The Elephant Trust — Autumn 2026 Grants",
    organization: "The Elephant Trust",
    url: "https://www.elephanttrust.org.uk/",
    applicationUrl: "https://www.elephanttrust.org.uk/",
    category: "arts_visual_photography",
    eligibilityText: "United Kingdom; visual artists and small arts organizations",
    focusText: "Visual art; new work; exhibitions",
    amountText: "£2,000–£5,000",
    windowText: "Deadline: Oct 18, 2026",
    sourceItemId: "the-elephant-trust-autumn-2026-grants",
  },
  {
    title: "Kickstarter Creative Capital x Culture Fund",
    organization: "Kickstarter Creative Capital x Culture Fund",
    url: "https://www.kickstarter.com/creative-capital",
    applicationUrl: "https://www.kickstarter.com/creative-capital",
    category: "arts_multidisciplinary",
    eligibilityText: "Creators in supported Kickstarter countries, including U.S.",
    focusText: "Music; film; photography; art; theater; dance; fashion",
    amountText: "At least $1,000 for selected projects",
    windowText: "Rolling through Dec 31, 2026",
    sourceItemId: "kickstarter-creative-capital-x-culture-fund",
  },
  {
    title: "Africa No Filter — Kekere Storytellers Fund",
    organization: "Africa No Filter",
    url: "https://africanofilter.org/grants",
    applicationUrl: "https://africanofilter.org/grants",
    category: "arts_multidisciplinary",
    eligibilityText: "Africa and African diaspora; creators under 35; see country rules",
    focusText: "Music; photography; digital storytelling; content creation",
    amountText: "$500–$3,000",
    windowText: "Open through Dec 31, 2026",
    sourceItemId: "africa-no-filter-kekere-storytellers-fund",
  },
  {
    title: "Amarte Fonds — Development Contribution",
    organization: "Amarte Fonds",
    url: "https://amarte.nl/",
    applicationUrl: "https://amarte.nl/",
    category: "arts_multidisciplinary",
    eligibilityText: "Netherlands and Caribbean part of the Kingdom; individual artists",
    focusText: "Music; film; visual art; theater; literature; interdisciplinary",
    amountText: "Up to €2,750",
    windowText: "Rolling",
    sourceItemId: "amarte-fonds-development-contribution",
  },
  {
    title: "Amarte Fonds — Project Contribution",
    organization: "Amarte Fonds",
    url: "https://amarte.nl/",
    applicationUrl: "https://amarte.nl/",
    category: "arts_multidisciplinary",
    eligibilityText: "Netherlands and Caribbean part of the Kingdom; artists and makers",
    focusText: "Music; film; visual art; theater; literature; interdisciplinary",
    amountText: "Up to €5,500",
    windowText: "Rolling",
    sourceItemId: "amarte-fonds-project-contribution",
  },
  {
    title: "Mondriaan Fund — Artist Project",
    organization: "Mondriaan Fund",
    url: "https://www.mondriaanfonds.nl/en/apply-for-a-grant/",
    applicationUrl: "https://www.mondriaanfonds.nl/en/apply-for-a-grant/",
    category: "arts_visual_photography",
    eligibilityText: "Netherlands/Caribbean Netherlands; eligible professional visual artists",
    focusText: "Photography; audiovisual; digital; sound; visual art/new media",
    amountText: "Fixed support approx. €2,785/month for up to 6 months or flexible support",
    windowText: "Rolling",
    sourceItemId: "mondriaan-fund-artist-project",
  },
  {
    title: "Creative Australia — First Nations Arts d/Deaf and/or Disabilities Project Fund",
    organization: "Creative Australia",
    url: "https://creative.gov.au/",
    applicationUrl: "https://creative.gov.au/",
    category: "arts_multidisciplinary",
    eligibilityText: "Australia; eligible First Nations d/Deaf and/or disabled artists",
    focusText: "All art forms, including music, film, photography and visual arts",
    amountText: "AUD $5,000–$10,000",
    windowText: "Deadline: Oct 13, 2026",
    sourceItemId: "creative-australia-first-nations-arts-d-deaf-and-or-disabilities-project-fund",
  },
  {
    title: "Vimeo Short Film Grant",
    organization: "Vimeo Short Film Grant",
    url: "https://vimeo.com/shortfilmgrant",
    applicationUrl: "https://vimeo.com/shortfilmgrant",
    category: "arts_film_media",
    eligibilityText: "U.S. & Canada; emerging directors 18+ with 2+ shorts and no feature directing credit",
    focusText: "Film; short narrative/documentary production",
    amountText: "Cash production grant + mentorship; amount per current program terms",
    windowText: "Deadline: Oct 16, 2026, 11:59 p.m. ET",
    sourceItemId: "vimeo-short-film-grant",
  },
  {
    title: "Pandora Short Film Grant",
    organization: "Pandora Short Film Grant",
    url: "https://pandora.org/",
    applicationUrl: "https://pandora.org/",
    category: "arts_film_media",
    eligibilityText: "U.S.; early-career filmmakers",
    focusText: "Film; short-film production",
    amountText: "$12,000 + production support",
    windowText: "Deadline: Oct 1, 2026",
    sourceItemId: "pandora-short-film-grant",
  },
  {
    title: "Frameline Completion Fund 2027",
    organization: "Frameline Completion Fund 2027",
    url: "https://www.frameline.org/artist-development/completion-fund",
    applicationUrl: "https://www.frameline.org/artist-development/completion-fund",
    category: "arts_film_media",
    eligibilityText: "Worldwide; LGBTQ+ films at least ~90% through production",
    focusText: "Film; documentary; narrative; experimental; animation; episodic",
    amountText: "$1,000–$5,000 standard grants",
    windowText: "Open Aug 31–Oct 9, 2026",
    sourceItemId: "frameline-completion-fund-2027",
  },
  {
    title: "Jewish Film Institute Grants 2027",
    organization: "Jewish Film Institute Grants 2027",
    url: "https://jfi.org/for-filmmakers/grants/application-guidelines",
    applicationUrl: "https://jfi.org/for-filmmakers/grants/application-guidelines",
    category: "arts_film_media",
    eligibilityText: "Worldwide; independent films/media exploring Jewish history, life, culture or identity; strong rough cut required",
    focusText: "Film; documentary; narrative; shorts; episodic/web series",
    amountText: "Completion funding; recent cycle awarded $95,000 across 6 projects",
    windowText: "Applications open Oct 2026; Phase 1 deadlines in Nov/Dec 2026",
    sourceItemId: "jewish-film-institute-grants-2027",
  },
  {
    title: "First Flights Short Film Fund",
    organization: "First Flights Short Film Fund",
    url: "https://www.first-flights.com/short-film-fund",
    applicationUrl: "https://www.first-flights.com/short-film-fund",
    category: "arts_film_media",
    eligibilityText: "Worldwide filmmakers; see project/rights rules",
    focusText: "Film; short film",
    amountText: "Up to £7,000 / approx. $10,000 + in-kind production awards",
    windowText: "Deadline: Oct 31, 2026",
    sourceItemId: "first-flights-short-film-fund",
  },
  {
    title: "NRDC Climate Storytelling Fellowship",
    organization: "NRDC Climate Storytelling Fellowship",
    url: "https://www.nrdc.org/stories/climate-storytelling-fellowship",
    applicationUrl: "https://www.nrdc.org/stories/climate-storytelling-fellowship",
    category: "arts_film_media",
    eligibilityText: "Eligible screenwriters; see current Black List fellowship rules",
    focusText: "Screenwriting; film/TV; climate storytelling",
    amountText: "$20,000 per fellow + mentorship",
    windowText: "Deadline: Dec 4, 2026",
    sourceItemId: "nrdc-climate-storytelling-fellowship",
  },
  {
    title: "CFA Institute × IMGN Filmmaker Grant",
    organization: "CFA Institute × IMGN Filmmaker Grant",
    url: "https://form.jotform.com/CFA_Institute/cfa--imgn-grant-application",
    applicationUrl: "https://form.jotform.com/CFA_Institute/cfa--imgn-grant-application",
    category: "arts_film_media",
    eligibilityText: "U.S.-based filmmakers 18+; original narrative/documentary projects",
    focusText: "Film; narrative; documentary",
    amountText: "$4,500",
    windowText: "Deadline: Dec 31, 2026",
    sourceItemId: "cfa-institute-imgn-filmmaker-grant",
  },
  {
    title: "Field of Vision — Documentary Commissions",
    organization: "Field of Vision",
    url: "https://fieldofvision.org/submit",
    applicationUrl: "https://fieldofvision.org/submit",
    category: "arts_film_media",
    eligibilityText: "Worldwide documentary filmmakers; editorial fit required",
    focusText: "Documentary film; nonfiction media",
    amountText: "Production funding; varies by commission",
    windowText: "Rolling",
    sourceItemId: "field-of-vision-documentary-commissions",
  },
  {
    title: "Pulitzer Center — Global Reporting Grants",
    organization: "Pulitzer Center",
    url: "https://pulitzercenter.org/grants-fellowships",
    applicationUrl: "https://pulitzercenter.org/grants-fellowships",
    category: "arts_film_media",
    eligibilityText: "Worldwide journalists and storytellers; eligibility varies by project",
    focusText: "Photography; documentary video; audio; multimedia storytelling",
    amountText: "Often $5,000–$10,000; varies",
    windowText: "Rolling",
    sourceItemId: "pulitzer-center-global-reporting-grants",
  },
  {
    title: "British Council — Travel Grant Fund for Film & XR",
    organization: "British Council",
    url: "https://film.britishcouncil.org/opportunities/travel-grants-fund",
    applicationUrl: "https://film.britishcouncil.org/opportunities/travel-grants-fund",
    category: "arts_film_media",
    eligibilityText: "UK-based filmmakers and XR creators traveling internationally for eligible opportunities",
    focusText: "Film; XR; immersive media",
    amountText: "Typically £150–£1,500 for film travel; larger XR/lab support may apply",
    windowText: "Rolling",
    sourceItemId: "british-council-travel-grant-fund-for-film-xr",
  },
  {
    title: "BFI Doc Society Fund — Features Production",
    organization: "BFI Doc Society Fund",
    url: "https://docsociety.org/bfi-doc-society-fund/",
    applicationUrl: "https://docsociety.org/bfi-doc-society-fund/",
    category: "arts_film_media",
    eligibilityText: "UK documentary projects meeting BFI eligibility",
    focusText: "Documentary film",
    amountText: "Up to £150,000",
    windowText: "Rolling / periodic decision rounds",
    sourceItemId: "bfi-doc-society-fund-features-production",
  },
  {
    title: "BFI — Impact Feature Funding",
    organization: "BFI",
    url: "https://www.bfi.org.uk/get-funding-support",
    applicationUrl: "https://www.bfi.org.uk/get-funding-support",
    category: "arts_film_media",
    eligibilityText: "UK eligible production companies/projects",
    focusText: "Film; feature production",
    amountText: "Up to £1.25 million",
    windowText: "Rolling",
    sourceItemId: "bfi-impact-feature-funding",
  },
  {
    title: "BFI — Development Funding",
    organization: "BFI",
    url: "https://www.bfi.org.uk/get-funding-support",
    applicationUrl: "https://www.bfi.org.uk/get-funding-support",
    category: "arts_film_media",
    eligibilityText: "UK eligible producers/production companies",
    focusText: "Film; feature development",
    amountText: "Varies",
    windowText: "Rolling",
    sourceItemId: "bfi-development-funding",
  },
  {
    title: "European Media Art Platform — EMAP/EMARE 2027",
    organization: "European Media Art Platform",
    url: "https://www.emare.eu/",
    applicationUrl: "https://www.emare.eu/",
    category: "arts_film_media",
    eligibilityText: "Artists resident/tax-paying in eligible European countries",
    focusText: "Media art; film/video; digital art; sound; interactive work",
    amountText: "€4,000 artist grant + €4,000 project budget; travel/accommodation support",
    windowText: "Deadline: Nov 6, 2026",
    sourceItemId: "european-media-art-platform-emap-emare-2027",
  },
  {
    title: "Festival de Cannes — La Résidence",
    organization: "Festival de Cannes",
    url: "https://www.festival-cannes.com/en/take-part/la-residence/",
    applicationUrl: "https://www.festival-cannes.com/en/take-part/la-residence/",
    category: "arts_film_media",
    eligibilityText: "Emerging filmmakers/directors; international eligibility, excluding certain France-based applicants",
    focusText: "Film; screenwriting/directing",
    amountText: "Paris residency support; one €5,000 CNC grant per session",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "festival-de-cannes-la-residence",
  },
  {
    title: "Netherlands Film Production Incentive — Film Production",
    organization: "Netherlands Film Production Incentive",
    url: "https://www.filmfonds.nl/en/funding/production-incentive",
    applicationUrl: "https://www.filmfonds.nl/en/funding/production-incentive",
    category: "arts_film_media",
    eligibilityText: "Eligible Dutch production companies / qualifying international co-productions",
    focusText: "Film production",
    amountText: "Up to 35% of qualifying production costs; max €3M",
    windowText: "Deadline: Oct 26, 2026",
    sourceItemId: "netherlands-film-production-incentive-film-production",
  },
  {
    title: "Netherlands Film Production Incentive — High-End Series",
    organization: "Netherlands Film Production Incentive",
    url: "https://www.filmfonds.nl/en/funding/production-incentive",
    applicationUrl: "https://www.filmfonds.nl/en/funding/production-incentive",
    category: "arts_film_media",
    eligibilityText: "Eligible Dutch production companies / qualifying series",
    focusText: "High-end television/series production",
    amountText: "Up to 35% of qualifying costs; caps apply",
    windowText: "Deadline: Oct 26, 2026",
    sourceItemId: "netherlands-film-production-incentive-high-end-series",
  },
  {
    title: "Script Pipeline First Look Project",
    organization: "Script Pipeline First Look Project",
    url: "https://scriptpipeline.com/first-look-project",
    applicationUrl: "https://scriptpipeline.com/first-look-project",
    category: "arts_film_media",
    eligibilityText: "Worldwide writers/filmmakers",
    focusText: "Screenwriting; film; television pilots",
    amountText: "$15,000 total across six winners",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "script-pipeline-first-look-project",
  },
  {
    title: "Basel House of Film — Filmmakers Residency",
    organization: "Basel House of Film",
    url: "https://www.baselfilm.ch/",
    applicationUrl: "https://www.baselfilm.ch/",
    category: "arts_film_media",
    eligibilityText: "International filmmakers; residency in Basel region, Switzerland",
    focusText: "Film; directing; screenwriting; development",
    amountText: "Housing + travel/living support; varies",
    windowText: "Rolling",
    sourceItemId: "basel-house-of-film-filmmakers-residency",
  },
  {
    title: "European Media Art Festival — Awards / Media Art Call",
    organization: "European Media Art Festival",
    url: "https://www.emaf.de/",
    applicationUrl: "https://www.emaf.de/",
    category: "arts_film_media",
    eligibilityText: "International media artists/filmmakers",
    focusText: "Film; video; media art; installation",
    amountText: "Selected works receive screening/production support; awards vary",
    windowText: "Deadline: Dec 15, 2026",
    sourceItemId: "european-media-art-festival-awards-media-art-call",
  },
  {
    title: "Data Theatre Collaborative — Pilot Replication Grants",
    organization: "Data Theatre Collaborative",
    url: "https://www.athe.org/page/dtgrants",
    applicationUrl: "https://www.athe.org/page/dtgrants",
    category: "arts_theater_performance",
    eligibilityText: "Faculty, community researchers, artists and civic practitioners",
    focusText: "Theater; performance; data-driven interdisciplinary art",
    amountText: "Five grants of $5,000",
    windowText: "Deadline: Oct 1, 2026",
    sourceItemId: "data-theatre-collaborative-pilot-replication-grants",
  },
  {
    title: "Vermont Studio Center — Artist & Writer Fellowships",
    organization: "Vermont Studio Center",
    url: "https://vermontstudiocenter.org/fellowships",
    applicationUrl: "https://vermontstudiocenter.org/fellowships",
    category: "arts_visual_photography",
    eligibilityText: "Worldwide artists and writers",
    focusText: "Visual art; photography; writing; interdisciplinary",
    amountText: "Full/partial fellowship support for 2–4 week residencies",
    windowText: "Deadline: Sep 30, 2026",
    sourceItemId: "vermont-studio-center-artist-writer-fellowships",
  },
  {
    title: "Central Minnesota Arts Board — Arts Access Grant",
    organization: "Central Minnesota Arts Board",
    url: "https://www.centralmnartsboard.org/grants/calendar/",
    applicationUrl: "https://www.centralmnartsboard.org/grants/calendar/",
    category: "arts_multidisciplinary",
    eligibilityText: "Central Minnesota eligible applicants; see county/service-area rules",
    focusText: "Music; film/media; photography; visual/performance arts",
    amountText: "Varies by program",
    windowText: "Rolling through FY27 while funds remain",
    sourceItemId: "central-minnesota-arts-board-arts-access-grant",
  },
  {
    title: "Central Minnesota Arts Board — Artist Learning Grant",
    organization: "Central Minnesota Arts Board",
    url: "https://www.centralmnartsboard.org/grants/calendar/",
    applicationUrl: "https://www.centralmnartsboard.org/grants/calendar/",
    category: "arts_multidisciplinary",
    eligibilityText: "Central Minnesota individual artists in eligible counties",
    focusText: "Music; film/media; photography; visual/performance arts; professional development",
    amountText: "Varies by program",
    windowText: "Rolling through May 21, 2027; open now",
    sourceItemId: "central-minnesota-arts-board-artist-learning-grant",
  },
  {
    title: "Amber Grant for Women (WomensNet)",
    organization: "Amber Grant for Women (WomensNet)",
    url: "https://ambergrantsforwomen.com/get-an-amber-grant/apply-now/",
    applicationUrl: "https://ambergrantsforwomen.com/get-an-amber-grant/apply-now/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S. & Canada; women who own at least 50% of the business",
    focusText: "Any business, including creative, design and maker businesses",
    amountText: "$10,000 monthly + three $50,000 year-end awards",
    windowText: "Rolling; apply anytime",
    sourceItemId: "amber-grant-for-women-womensnet",
  },
  {
    title: "NASE Growth Grants",
    organization: "NASE Growth Grants",
    url: "https://www.nase.org/become-a-member/benefits/grants",
    applicationUrl: "https://www.nase.org/become-a-member/benefits/grants",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; National Association for the Self-Employed members",
    focusText: "Any self-employed/small business, including creative businesses",
    amountText: "$4,000",
    windowText: "Quarterly; next cycle deadline Dec 2026",
    sourceItemId: "nase-growth-grants",
  },
  {
    title: "Hello Alice Small Business Grants & Funding Marketplace",
    organization: "Hello Alice Small Business Grants & Funding Marketplace",
    url: "https://www.helloalice.com/small-business-grants-and-funding",
    applicationUrl: "https://www.helloalice.com/small-business-grants-and-funding",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S. small business owners; eligibility varies by fund",
    focusText: "Any small business, including creative and community-facing businesses",
    amountText: "Varies by fund; typically $5,000–$25,000",
    windowText: "Rolling; hosts rotating sponsor-funded grants with their own windows",
    sourceItemId: "hello-alice-small-business-grants-funding-marketplace",
  },
  {
    title: "Verizon Small Business Digital Ready — $10,000 National Grant",
    organization: "Verizon Small Business Digital Ready",
    url: "https://digitalready.verizonwireless.com/grants",
    applicationUrl: "https://digitalready.verizonwireless.com/grants",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S. small business owners with a free Digital Ready account",
    focusText: "Any small business investing in digital growth tools",
    amountText: "$10,000",
    windowText: "Learning modules due Dec 7, 2026; applications reviewed monthly through Dec 2026",
    sourceItemId: "verizon-small-business-digital-ready-10-000-national-grant",
  },
  {
    title: "SoGal Foundation — Black Founder Startup Grant",
    organization: "SoGal Foundation",
    url: "https://www.sogalfoundation.org/",
    applicationUrl: "https://www.sogalfoundation.org/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; Black women and Black nonbinary entrepreneurs",
    focusText: "Any startup or small business",
    amountText: "$5,000–$10,000",
    windowText: "Rolling",
    sourceItemId: "sogal-foundation-black-founder-startup-grant",
  },
  {
    title: "HerRise MicroGrant",
    organization: "HerRise MicroGrant",
    url: "https://www.hersuitespot.com/herrise/",
    applicationUrl: "https://www.hersuitespot.com/herrise/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; for-profit small businesses at least 51% owned by women of color",
    focusText: "Any small business, including creative and community-impact ventures",
    amountText: "$1,000",
    windowText: "Monthly; apply by 11:59 p.m. on the last day of each month",
    sourceItemId: "herrise-microgrant",
  },
  {
    title: "IFundWomen Universal Grant Application",
    organization: "IFundWomen Universal Grant Application",
    url: "https://ifundwomen.com/grants",
    applicationUrl: "https://ifundwomen.com/grants",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; women-owned/led businesses",
    focusText: "Any business, including creative and consumer brands",
    amountText: "Varies; single application pools multiple funder opportunities",
    windowText: "Rolling",
    sourceItemId: "ifundwomen-universal-grant-application",
  },
  {
    title: "Comcast RISE",
    organization: "Comcast RISE",
    url: "https://www.comcastrise.com/",
    applicationUrl: "https://www.comcastrise.com/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; small businesses, with priority to women- and minority-owned businesses",
    focusText: "Any small business",
    amountText: "$5,000–$10,000 cash plus marketing, technology and coaching support",
    windowText: "Periodic application windows; monitor site for next round",
    sourceItemId: "comcast-rise",
  },
  {
    title: "Google for Startups Latino Founders Fund",
    organization: "Google for Startups Latino Founders Fund",
    url: "https://startup.google.com/programs/latino-founders-fund/united-states/",
    applicationUrl: "https://startup.google.com/programs/latino-founders-fund/united-states/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S.; Latino-founded startups",
    focusText: "Tech-enabled and scalable startups, including creative-tech",
    amountText: "$150,000 cash award (non-dilutive)",
    windowText: "Rolling; currently open",
    sourceItemId: "google-for-startups-latino-founders-fund",
  },
  {
    title: "Google for Startups Black Founders Fund",
    organization: "Google for Startups Black Founders Fund",
    url: "https://startup.google.com/programs/black-founders-fund/",
    applicationUrl: "https://startup.google.com/programs/black-founders-fund/",
    category: "business_creative_entrepreneur",
    eligibilityText: "U.S., Brazil and Europe; Black-founded startups",
    focusText: "Tech-enabled and scalable startups, including creative-tech",
    amountText: "Non-dilutive cash award + up to $100,000 in Google Cloud credits",
    windowText: "Rolling; currently open",
    sourceItemId: "google-for-startups-black-founders-fund",
  },
  {
    title: "Tony Elumelu Foundation Entrepreneurship Programme",
    organization: "Tony Elumelu Foundation Entrepreneurship Programme",
    url: "https://www.tonyelumelufoundation.org/",
    applicationUrl: "https://www.tonyelumelufoundation.org/",
    category: "business_creative_entrepreneur",
    eligibilityText: "Africa; start-ups 0–3 years old, founders 18+, nationals of an African country",
    focusText: "Any sector, including creative and community-focused businesses",
    amountText: "$5,000 non-refundable seed capital + training and mentorship",
    windowText: "2026 window closed (Jan 1–Mar 1, 2026); next cycle expected to open Jan 2027",
    sourceItemId: "tony-elumelu-foundation-entrepreneurship-programme",
  },
  {
    title: "The Prince's Trust / King's Trust Enterprise Programme",
    organization: "The Prince's Trust / King's Trust Enterprise Programme",
    url: "https://www.kingstrust.org.uk/",
    applicationUrl: "https://www.kingstrust.org.uk/",
    category: "business_creative_entrepreneur",
    eligibilityText: "UK; ages 18–30, unemployed or working fewer than 16 hrs/week",
    focusText: "Any business idea, including creative and community ventures",
    amountText: "Up to £5,000 non-repayable grant (plus optional £500–£25,000 loan)",
    windowText: "Rolling; ongoing enrollment",
    sourceItemId: "the-prince-s-trust-king-s-trust-enterprise-programme",
  },
  {
    title: "Shell LiveWIRE",
    organization: "Shell LiveWIRE",
    url: "https://www.shell-livewire.org/",
    applicationUrl: "https://www.shell-livewire.org/",
    category: "business_creative_entrepreneur",
    eligibilityText: "Multiple countries incl. UK, South Africa and Malaysia; entrepreneurs aged 16–30",
    focusText: "Any small or growing business",
    amountText: "£5,000 monthly award; £25,000 annual award",
    windowText: "Rolling; monthly Smarter Future Awards plus an annual Young Entrepreneur of the Year award",
    sourceItemId: "shell-livewire",
  },
  {
    title: "Global Innovation Fund (GIF)",
    organization: "Global Innovation Fund (GIF)",
    url: "https://www.globalinnovation.fund/apply-for-funding",
    applicationUrl: "https://www.globalinnovation.fund/apply-for-funding",
    category: "business_creative_entrepreneur",
    eligibilityText: "Worldwide; social enterprises, nonprofits and businesses serving people living on under $5/day",
    focusText: "Social enterprise; livelihoods; financial health; climate resilience",
    amountText: "$50,000–$15,000,000 depending on stage",
    windowText: "Rolling; no fixed deadline",
    sourceItemId: "global-innovation-fund-gif",
  },
  {
    title: "AWS IMAGINE Grant",
    organization: "AWS IMAGINE Grant",
    url: "https://pages.awscloud.com/aws-imagine-grant-guidelines-US-2026.html",
    applicationUrl: "https://pages.awscloud.com/aws-imagine-grant-guidelines-US-2026.html",
    category: "tech_nonprofit_tech",
    eligibilityText: "U.S. 501(c) nonprofits of any budget size using AWS cloud technology",
    focusText: "Nonprofit tech/cloud innovation",
    amountText: "Cash grant + AWS credits; award tiers vary by category (Pathfinder, Go Further Faster, Momentum to Modernize)",
    windowText: "2026 Round One deadline (Jun 5, 2026) has passed; monitor site for next round",
    sourceItemId: "aws-imagine-grant",
  },
  {
    title: "Microsoft Nonprofit Technology Grants & Credits (incl. AI for Good)",
    organization: "Microsoft Nonprofit Technology Grants & Credits (incl. AI for Good)",
    url: "https://www.microsoft.com/en-us/nonprofits/offers-for-nonprofits",
    applicationUrl: "https://www.microsoft.com/en-us/nonprofits/offers-for-nonprofits",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide 501(c)(3)-equivalent nonprofits verified via TechSoup",
    focusText: "Nonprofit technology, AI, accessibility and digital-skills projects",
    amountText: "Software/cloud donations plus select cash grants, typically $50,000–$500,000 for AI for Good awards",
    windowText: "Rolling",
    sourceItemId: "microsoft-nonprofit-technology-grants-credits-incl-ai-for-good",
  },
  {
    title: "TechSoup Technology Donations & Grants Hub",
    organization: "TechSoup Technology Donations & Grants Hub",
    url: "https://www.techsoup.org/",
    applicationUrl: "https://www.techsoup.org/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide verified nonprofits, charities and libraries",
    focusText: "Nonprofit technology infrastructure and software",
    amountText: "Discounted/donated software, hardware and cloud credits",
    windowText: "Rolling",
    sourceItemId: "techsoup-technology-donations-grants-hub",
  },
  {
    title: "Federal SBIR/STTR Awards",
    organization: "Federal SBIR/STTR Awards",
    url: "https://www.sbir.gov/",
    applicationUrl: "https://www.sbir.gov/",
    category: "tech_nonprofit_tech",
    eligibilityText: "U.S. small, for-profit R&D and technology companies",
    focusText: "Technology; scientific and engineering innovation",
    amountText: "Phase I typically up to approx. $314,000; Phase II up to approx. $1.2M+ (amounts vary by agency)",
    windowText: "Rolling; agency-specific solicitation deadlines throughout the year",
    sourceItemId: "federal-sbir-sttr-awards",
  },
  {
    title: "Mozilla Technology Fund",
    organization: "Mozilla Technology Fund",
    url: "https://www.mozillafoundation.org/en/what-we-fund/",
    applicationUrl: "https://www.mozillafoundation.org/en/what-we-fund/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide open-source project teams",
    focusText: "Open-source technology; internet health; AI auditing and transparency tools",
    amountText: "Up to $50,000 + 12-month mentorship cohort",
    windowText: "Rolling themed open calls; check site for the current call",
    sourceItemId: "mozilla-technology-fund",
  },
  {
    title: "GitHub Secure Open Source Fund",
    organization: "GitHub Secure Open Source Fund",
    url: "https://github.com/open-source/github-secure-open-source-fund",
    applicationUrl: "https://github.com/open-source/github-secure-open-source-fund",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide open-source maintainers (individuals or teams of up to 3) with an active GitHub profile",
    focusText: "Open-source project security improvements",
    amountText: "Funding tied to completed security work; amount varies by session",
    windowText: "Rolling sessions (a recent session closed Aug 18, 2026); check site for the next session",
    sourceItemId: "github-secure-open-source-fund",
  },
  {
    title: "Patrick J. McGovern Foundation — AI Fluency & Capacity Building Grants",
    organization: "Patrick J. McGovern Foundation",
    url: "https://www.mcgovern.org/grants/",
    applicationUrl: "https://www.mcgovern.org/grants/",
    category: "tech_nonprofit_tech",
    eligibilityText: "Worldwide nonprofits and public institutions with existing data assets",
    focusText: "AI literacy; responsible AI deployment; data capacity building",
    amountText: "Varies",
    windowText: "Rolling (a recent cycle deadline was Jul 1, 2026); check site for the next window",
    sourceItemId: "patrick-j-mcgovern-foundation-ai-fluency-capacity-building-grants",
  },
  {
    title: "PFund Foundation Community Grants Program",
    organization: "PFund Foundation Community Grants Program",
    url: "https://www.pfundonline.org/grants/",
    applicationUrl: "https://www.pfundonline.org/grants/",
    category: "community_civic",
    eligibilityText: "Upper Midwest (MN, ND, SD, WI, IA); LGBTQ+-serving nonprofits",
    focusText: "Community programs; LGBTQ+ services",
    amountText: "Varies",
    windowText: "Deadline: Oct 13, 2026",
    sourceItemId: "pfund-foundation-community-grants-program",
  },
  {
    title: "Project for Public Spaces — Community Placemaking Grants",
    organization: "Project for Public Spaces",
    url: "https://www.pps.org/community-placemaking-grants",
    applicationUrl: "https://www.pps.org/community-placemaking-grants",
    category: "community_civic",
    eligibilityText: "U.S.; community organizations and coalitions",
    focusText: "Public space; placemaking; community-led design",
    amountText: "Varies",
    windowText: "Deadline: Oct 26, 2026, 11:59 p.m. ET",
    sourceItemId: "project-for-public-spaces-community-placemaking-grants",
  },
  {
    title: "National Trust Preservation Funds",
    organization: "National Trust Preservation Funds",
    url: "https://savingplaces.org/preservation-funds",
    applicationUrl: "https://savingplaces.org/preservation-funds",
    category: "community_civic",
    eligibilityText: "U.S.; public agencies and 501(c)(3)/other nonprofit organizations in eligible states",
    focusText: "Historic preservation planning and education",
    amountText: "$2,500–$5,000",
    windowText: "Deadline: Oct 1, 2026 (one of three annual cycles: Feb/Jun/Oct)",
    sourceItemId: "national-trust-preservation-funds",
  },
  {
    title: "IMLS Museums for America",
    organization: "IMLS Museums for America",
    url: "https://www.imls.gov/find-funding/funding-opportunities/grant-programs/museums-for-america",
    applicationUrl: "https://www.imls.gov/find-funding/funding-opportunities/grant-programs/museums-for-america",
    category: "community_civic",
    eligibilityText: "U.S. museums of any discipline or size",
    focusText: "Museum programs; community services; collections care",
    amountText: "$5,000–$350,000",
    windowText: "Deadline: Nov 13, 2026",
    sourceItemId: "imls-museums-for-america",
  },
  {
    title: "IMLS Inspire! Grants for Small Museums",
    organization: "IMLS Inspire! Grants for Small Museums",
    url: "https://www.imls.gov/find-funding/funding-opportunities/grant-programs/inspire-grants-for-small-museums",
    applicationUrl: "https://www.imls.gov/find-funding/funding-opportunities/grant-programs/inspire-grants-for-small-museums",
    category: "community_civic",
    eligibilityText: "U.S. small, rural or previously unfunded museums",
    focusText: "Museum capacity-building; community engagement",
    amountText: "$5,000–$75,000",
    windowText: "Deadline: Nov 13, 2026",
    sourceItemId: "imls-inspire-grants-for-small-museums",
  },
  {
    title: "Walmart.org Spark Good Local Grants",
    organization: "Walmart.org Spark Good Local Grants",
    url: "https://www.walmart.org/how-we-give/open-applications",
    applicationUrl: "https://www.walmart.org/how-we-give/open-applications",
    category: "community_civic",
    eligibilityText: "U.S. 501(c)(3) public charities and eligible faith-based organizations near a Walmart, Sam's Club or Distribution Center",
    focusText: "Local community needs; food security; workforce development; community services",
    amountText: "$250–$5,000",
    windowText: "Cycle 3 open Aug 1–Nov 30, 2026",
    sourceItemId: "walmart-org-spark-good-local-grants",
  },
  {
    title: "Bank of America Neighborhood Builders",
    organization: "Bank of America Neighborhood Builders",
    url: "https://about.bankofamerica.com/en/making-an-impact/grant-funding-for-nonprofits-sponsorship-programs",
    applicationUrl: "https://about.bankofamerica.com/en/making-an-impact/grant-funding-for-nonprofits-sponsorship-programs",
    category: "community_civic",
    eligibilityText: "U.S. 501(c)(3) nonprofits with 2+ years tenure focused on stable housing or income creation",
    focusText: "Community and economic development; nonprofit leadership development",
    amountText: "$100,000–$400,000 over two years plus leadership training",
    windowText: "2026 cycle closed (deadline was Jul 1, 2026); next cycle opens Spring 2027",
    sourceItemId: "bank-of-america-neighborhood-builders",
  },
];
