/**
 * Curated grants — batch 2 (added 2026-09-27 from user-provided links).
 *
 * Filtered to opportunities open to African (incl. Tanzanian) applicants
 * — see curated-grants.ts's header for why. This batch was already
 * heavily Africa-focused going in, so only a few entries were removed
 * (a Germany-university-residency program, a non-grant newsletter link,
 * and a US-focused corporate education grant).
 *
 * This batch came from a link-only research list — organization + URL,
 * no stated deadline or funding amount. windowText/amountText are left
 * null rather than guessed, so these entries show status "rolling" until
 * someone confirms and adds real dates (see lib/grants/classify-status.ts).
 *
 * Two sections from the source material were deliberately NOT included:
 * "International Networks" (membership platforms, not funding programs)
 * and "Opportunity Trackers" (aggregator/listing sites, not opportunities
 * themselves) — listing those as grants would have been misleading.
 */

import type { RawGrant } from "@/lib/grants/source-types";

export const CURATED_GRANTS_BATCH_2: RawGrant[] = [
  {
    title: "Creative Enterprise Programme — British Council x Nesta",
    organization: "Creative Enterprise Programme — British Council x Nesta",
    url: "https://www.britishcouncil.org/arts/creative-economy",
    applicationUrl: "https://www.britishcouncil.org/arts/creative-economy",
    category: "arts_multidisciplinary",
    focusText: "Creative economy grant/fund",
    sourceItemId: "creative-enterprise-programme-british-council-x-nesta",
  },
  {
    title: "ACP-EU Culture: Ignite Culture Fund (Eastern Africa)",
    organization: "ACP-EU Culture: Ignite Culture Fund (Eastern Africa)",
    url: "https://www.acp-ue-culture.eu",
    applicationUrl: "https://www.acp-ue-culture.eu",
    category: "arts_multidisciplinary",
    focusText: "Creative economy grant/fund",
    sourceItemId: "acp-eu-culture-ignite-culture-fund-eastern-africa",
  },
  {
    title: "HEVA Fund",
    organization: "HEVA Fund",
    url: "https://www.hevafund.com",
    applicationUrl: "https://www.hevafund.com",
    category: "arts_multidisciplinary",
    focusText: "Creative economy grant/fund",
    sourceItemId: "heva-fund",
  },
  {
    title: "Goethe-Institut Cultural Projects",
    organization: "Goethe-Institut Cultural Projects",
    url: "https://www.goethe.de",
    applicationUrl: "https://www.goethe.de",
    category: "arts_multidisciplinary",
    focusText: "Creative economy grant/fund",
    sourceItemId: "goethe-institut-cultural-projects",
  },
  {
    title: "Prince Claus Fund",
    organization: "Prince Claus Fund",
    url: "https://princeclausfund.org",
    applicationUrl: "https://princeclausfund.org",
    category: "arts_multidisciplinary",
    focusText: "Creative economy grant/fund",
    sourceItemId: "prince-claus-fund",
  },
  {
    title: "Creative DNA — British Council",
    organization: "Creative DNA — British Council",
    url: "https://www.britishcouncil.org/arts/creative-economy",
    applicationUrl: "https://www.britishcouncil.org/arts/creative-economy",
    category: "business_creative_entrepreneur",
    focusText: "Creative business accelerator / incubator",
    sourceItemId: "creative-dna-british-council",
  },
  {
    title: "CcHUB — Creative Economy programs",
    organization: "CcHUB — Creative Economy programs",
    url: "https://cchub.africa",
    applicationUrl: "https://cchub.africa",
    category: "business_creative_entrepreneur",
    focusText: "Creative business accelerator / incubator",
    sourceItemId: "cchub-creative-economy-programs",
  },
  {
    title: "Africa No Filter programs",
    organization: "Africa No Filter programs",
    url: "https://africanofilter.org",
    applicationUrl: "https://africanofilter.org",
    category: "business_creative_entrepreneur",
    focusText: "Creative business accelerator / incubator",
    sourceItemId: "africa-no-filter-programs",
  },
  {
    title: "Orange Corners",
    organization: "Orange Corners",
    url: "https://www.orangecorners.com",
    applicationUrl: "https://www.orangecorners.com",
    category: "business_creative_entrepreneur",
    focusText: "Creative business accelerator / incubator",
    sourceItemId: "orange-corners",
  },
  {
    title: "Moleskine Foundation — Creativity Pioneers Fund",
    organization: "Moleskine Foundation — Creativity Pioneers Fund",
    url: "https://moleskinefoundation.org",
    applicationUrl: "https://moleskinefoundation.org",
    category: "business_creative_entrepreneur",
    focusText: "Creative business accelerator / incubator",
    sourceItemId: "moleskine-foundation-creativity-pioneers-fund",
  },
  {
    title: "Design Indaba — Emerging Creatives",
    organization: "Design Indaba — Emerging Creatives",
    url: "https://www.designindaba.com",
    applicationUrl: "https://www.designindaba.com",
    category: "arts_multidisciplinary",
    focusText: "Showcase / competition for creative talent",
    sourceItemId: "design-indaba-emerging-creatives",
  },
  {
    title: "Biennale of Luanda — UNESCO",
    organization: "Biennale of Luanda — UNESCO",
    url: "https://www.unesco.org",
    applicationUrl: "https://www.unesco.org",
    category: "arts_multidisciplinary",
    focusText: "Showcase / competition for creative talent",
    sourceItemId: "biennale-of-luanda-unesco",
  },
  {
    title: "Africa Creative Market (not verified; closest match is Afreximbank CANEX)",
    organization: "Africa Creative Market (not verified; closest match is Afreximbank CANEX)",
    url: "https://www.afreximbank.com",
    applicationUrl: "https://www.afreximbank.com",
    category: "arts_multidisciplinary",
    focusText: "Showcase / competition for creative talent",
    sourceItemId: "africa-creative-market-not-verified-closest-match-is-afreximbank-canex",
  },
  {
    title: "Creative Business Cup",
    organization: "Creative Business Cup",
    url: "https://creativebusinesscup.com",
    applicationUrl: "https://creativebusinesscup.com",
    category: "arts_multidisciplinary",
    focusText: "Showcase / competition for creative talent",
    sourceItemId: "creative-business-cup",
  },
  {
    title: "Pro Helvetia Residencies (Switzerland)",
    organization: "Pro Helvetia Residencies (Switzerland)",
    url: "https://prohelvetia.ch",
    applicationUrl: "https://prohelvetia.ch",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "pro-helvetia-residencies-switzerland",
  },
  {
    title: "Goethe-Institut Residency Programs (Germany)",
    organization: "Goethe-Institut Residency Programs (Germany)",
    url: "https://www.goethe.de",
    applicationUrl: "https://www.goethe.de",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "goethe-institut-residency-programs-germany",
  },
  {
    title: "British Council Creative Economy Residency",
    organization: "British Council Creative Economy Residency",
    url: "https://www.britishcouncil.org/arts/creative-economy",
    applicationUrl: "https://www.britishcouncil.org/arts/creative-economy",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "british-council-creative-economy-residency",
  },
  {
    title: "Prince Claus Mobility & Residency Grants",
    organization: "Prince Claus Mobility & Residency Grants",
    url: "https://princeclausfund.org",
    applicationUrl: "https://princeclausfund.org",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "prince-claus-mobility-residency-grants",
  },
  {
    title: "Africa No Filter Residencies",
    organization: "Africa No Filter Residencies",
    url: "https://africanofilter.org",
    applicationUrl: "https://africanofilter.org",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "africa-no-filter-residencies",
  },
  {
    title: "Akademie Schloss Solitude (Germany)",
    organization: "Akademie Schloss Solitude (Germany)",
    url: "https://www.akademie-solitude.de",
    applicationUrl: "https://www.akademie-solitude.de",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "akademie-schloss-solitude-germany",
  },
  {
    title: "Art Omi Residency (USA)",
    organization: "Art Omi Residency (USA)",
    url: "https://artomi.org",
    applicationUrl: "https://artomi.org",
    category: "arts_residencies",
    focusText: "Artist residency programme",
    sourceItemId: "art-omi-residency-usa",
  },
  {
    title: "Funding the Commons Residency",
    organization: "Funding the Commons Residency",
    url: "https://fundingthecommons.io/residencies",
    applicationUrl: "https://fundingthecommons.io/residencies",
    category: "tech_nonprofit_tech",
    focusText: "Public goods / decentralized tech residency",
    sourceItemId: "funding-the-commons-residency",
  },
  {
    title: "stART Foundation Residencies (Warsaw, Poland)",
    organization: "stART Foundation Residencies (Warsaw, Poland)",
    url: "https://start-foundation.eu/residencies",
    applicationUrl: "https://start-foundation.eu/residencies",
    category: "tech_nonprofit_tech",
    focusText: "Public goods / decentralized tech residency",
    sourceItemId: "start-foundation-residencies-warsaw-poland",
  },
  {
    title: "DWeb Fellowship (DWeb Camp)",
    organization: "DWeb Fellowship (DWeb Camp)",
    url: "https://dwebcamp.org/fellowships",
    applicationUrl: "https://dwebcamp.org/fellowships",
    category: "tech_nonprofit_tech",
    focusText: "Decentralized tech / public goods fellowship",
    sourceItemId: "dweb-fellowship-dweb-camp",
  },
  {
    title: "Catalyze Research Fellowship (Pantera Capital)",
    organization: "Catalyze Research Fellowship (Pantera Capital)",
    url: "https://catalyze.panteracapital.com",
    applicationUrl: "https://catalyze.panteracapital.com",
    category: "tech_nonprofit_tech",
    focusText: "Decentralized tech / public goods fellowship",
    sourceItemId: "catalyze-research-fellowship-pantera-capital",
  },
  {
    title: "Kleros Fellowship of Justice",
    organization: "Kleros Fellowship of Justice",
    url: "https://kleros.io/en/fellowship",
    applicationUrl: "https://kleros.io/en/fellowship",
    category: "tech_nonprofit_tech",
    focusText: "Decentralized tech / public goods fellowship",
    sourceItemId: "kleros-fellowship-of-justice",
  },
  {
    title: "Ritual Fellowship",
    organization: "Ritual Fellowship",
    url: "https://ritualfoundation.org",
    applicationUrl: "https://ritualfoundation.org",
    category: "tech_nonprofit_tech",
    focusText: "Decentralized tech / public goods fellowship",
    sourceItemId: "ritual-fellowship",
  },
  {
    title: "DeSciWorld Fellowship",
    organization: "DeSciWorld Fellowship",
    url: "https://desci.world/fellowship",
    applicationUrl: "https://desci.world/fellowship",
    category: "tech_nonprofit_tech",
    focusText: "Decentralized tech / public goods fellowship",
    sourceItemId: "desciworld-fellowship",
  },
  {
    title: "JUST Open Source Grants",
    organization: "JUST Open Source Grants",
    url: "https://justopensource.io/grants",
    applicationUrl: "https://justopensource.io/grants",
    category: "tech_nonprofit_tech",
    focusText: "Open source / public goods grant",
    sourceItemId: "just-open-source-grants",
  },
  {
    title: "Grants for Sustainable AI (Patina Foundation)",
    organization: "Grants for Sustainable AI (Patina Foundation)",
    url: "https://patinafoundation.io/grants",
    applicationUrl: "https://patinafoundation.io/grants",
    category: "tech_nonprofit_tech",
    focusText: "Open source / public goods grant",
    sourceItemId: "grants-for-sustainable-ai-patina-foundation",
  },
  {
    title: "Mastercard Foundation EdTech Fellowship — Sahara Consult Tanzania",
    organization: "Mastercard Foundation EdTech Fellowship — Sahara Consult Tanzania",
    url: "https://mastercardfdn.org",
    applicationUrl: "https://mastercardfdn.org",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "mastercard-foundation-edtech-fellowship-sahara-consult-tanzania",
  },
  {
    title: "FUNGUO Innovation Programme (UNDP Tanzania)",
    organization: "FUNGUO Innovation Programme (UNDP Tanzania)",
    url: "https://www.undp.org/tanzania",
    applicationUrl: "https://www.undp.org/tanzania",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "funguo-innovation-programme-undp-tanzania",
  },
  {
    title: "Innovating Education in Africa (African Union)",
    organization: "Innovating Education in Africa (African Union)",
    url: "https://au.int",
    applicationUrl: "https://au.int",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "innovating-education-in-africa-african-union",
  },
  {
    title: "AWS Education Equity Initiative",
    organization: "AWS Education Equity Initiative",
    url: "https://aws.amazon.com/education/",
    applicationUrl: "https://aws.amazon.com/education/",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "aws-education-equity-initiative",
  },
  {
    title: "IFC Education Innovation Grant (unverified link)",
    organization: "IFC Education Innovation Grant (unverified link)",
    url: "https://nextbillion.net/business-development/education-innovation-grant/",
    applicationUrl: "https://nextbillion.net/business-development/education-innovation-grant/",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "ifc-education-innovation-grant-unverified-link",
  },
  {
    title: "Sentient Foundation — Open Source AGI Grant & Investment Program",
    organization: "Sentient Foundation — Open Source AGI Grant & Investment Program",
    url: "https://sentient.foundation",
    applicationUrl: "https://sentient.foundation",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "sentient-foundation-open-source-agi-grant-investment-program",
  },
  {
    title: "Schmidt Sciences — AI programmes",
    organization: "Schmidt Sciences — AI programmes",
    url: "https://www.schmidtsciences.org",
    applicationUrl: "https://www.schmidtsciences.org",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "schmidt-sciences-ai-programmes",
  },
  {
    title: "OpenAI Academy & developer programmes",
    organization: "OpenAI Academy & developer programmes",
    url: "https://academy.openai.com",
    applicationUrl: "https://academy.openai.com",
    category: "tech_nonprofit_tech",
    focusText: "EdTech / AI-powered learning programme",
    sourceItemId: "openai-academy-developer-programmes",
  },
  {
    title: "CAP Prize — Contemporary African Photography Prize",
    organization: "CAP Prize — Contemporary African Photography Prize",
    url: "https://www.capprize.com",
    applicationUrl: "https://www.capprize.com",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "cap-prize-contemporary-african-photography-prize",
  },
  {
    title: "Musée du quai Branly Photography Award",
    organization: "Musée du quai Branly Photography Award",
    url: "https://www.quaibranly.fr",
    applicationUrl: "https://www.quaibranly.fr",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "musee-du-quai-branly-photography-award",
  },
  {
    title: "Henrike Grohs Art Award (Goethe-Institut)",
    organization: "Henrike Grohs Art Award (Goethe-Institut)",
    url: "https://www.goethe.de",
    applicationUrl: "https://www.goethe.de",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "henrike-grohs-art-award-goethe-institut",
  },
  {
    title: "Daniele Tamagni Grant",
    organization: "Daniele Tamagni Grant",
    url: "https://fastforward.photography/opportunity-location/africa/",
    applicationUrl: "https://fastforward.photography/opportunity-location/africa/",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "daniele-tamagni-grant",
  },
  {
    title: "World Press Photo Contest",
    organization: "World Press Photo Contest",
    url: "https://www.worldpressphoto.org",
    applicationUrl: "https://www.worldpressphoto.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "world-press-photo-contest",
  },
  {
    title: "World Press Photo — Joop Swart Masterclass",
    organization: "World Press Photo — Joop Swart Masterclass",
    url: "https://www.worldpressphoto.org",
    applicationUrl: "https://www.worldpressphoto.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "world-press-photo-joop-swart-masterclass",
  },
  {
    title: "African Photojournalism Database (APJD)",
    organization: "African Photojournalism Database (APJD)",
    url: "https://www.worldpressphoto.org",
    applicationUrl: "https://www.worldpressphoto.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "african-photojournalism-database-apjd",
  },
  {
    title: "Magnum Foundation grants & fellowships",
    organization: "Magnum Foundation grants & fellowships",
    url: "https://www.magnumfoundation.org",
    applicationUrl: "https://www.magnumfoundation.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "magnum-foundation-grants-fellowships",
  },
  {
    title: "The Aftermath Project Grant",
    organization: "The Aftermath Project Grant",
    url: "https://www.theaftermathproject.org",
    applicationUrl: "https://www.theaftermathproject.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "the-aftermath-project-grant",
  },
  {
    title: "Alexia Foundation Grants",
    organization: "Alexia Foundation Grants",
    url: "https://www.alexiafoundation.org",
    applicationUrl: "https://www.alexiafoundation.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "alexia-foundation-grants",
  },
  {
    title: "Aperture Portfolio Prize",
    organization: "Aperture Portfolio Prize",
    url: "https://aperture.org",
    applicationUrl: "https://aperture.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "aperture-portfolio-prize",
  },
  {
    title: "Images Vevey — Grand Prix & Book Award",
    organization: "Images Vevey — Grand Prix & Book Award",
    url: "https://www.images.ch",
    applicationUrl: "https://www.images.ch",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "images-vevey-grand-prix-book-award",
  },
  {
    title: "National Geographic Society Explorer Grants",
    organization: "National Geographic Society Explorer Grants",
    url: "https://www.nationalgeographic.org",
    applicationUrl: "https://www.nationalgeographic.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "national-geographic-society-explorer-grants",
  },
  {
    title: "Getty Images Grants (Editorial / Creative)",
    organization: "Getty Images Grants (Editorial / Creative)",
    url: "https://www.gettyimages.com",
    applicationUrl: "https://www.gettyimages.com",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "getty-images-grants-editorial-creative",
  },
  {
    title: "Leica Oskar Barnack Award",
    organization: "Leica Oskar Barnack Award",
    url: "https://leica-oskar-barnack-award.com",
    applicationUrl: "https://leica-oskar-barnack-award.com",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "leica-oskar-barnack-award",
  },
  {
    title: "Sony World Photography Awards",
    organization: "Sony World Photography Awards",
    url: "https://www.worldphoto.org",
    applicationUrl: "https://www.worldphoto.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "sony-world-photography-awards",
  },
  {
    title: "LensCulture Awards",
    organization: "LensCulture Awards",
    url: "https://www.lensculture.com",
    applicationUrl: "https://www.lensculture.com",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "lensculture-awards",
  },
  {
    title: "W. Eugene Smith Grant",
    organization: "W. Eugene Smith Grant",
    url: "https://smithfund.org",
    applicationUrl: "https://smithfund.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "w-eugene-smith-grant",
  },
  {
    title: "Ian Parry Scholarship",
    organization: "Ian Parry Scholarship",
    url: "https://www.ianparry.org",
    applicationUrl: "https://www.ianparry.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "ian-parry-scholarship",
  },
  {
    title: "Inge Morath Award",
    organization: "Inge Morath Award",
    url: "https://ingemorath.org",
    applicationUrl: "https://ingemorath.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "inge-morath-award",
  },
  {
    title: "Hasselblad Foundation grants",
    organization: "Hasselblad Foundation grants",
    url: "https://www.hasselbladfoundation.org",
    applicationUrl: "https://www.hasselbladfoundation.org",
    category: "arts_visual_photography",
    focusText: "Photography prize / grant",
    sourceItemId: "hasselblad-foundation-grants",
  },
  {
    title: "Documentary Africa — EAccelerate Fund",
    organization: "Documentary Africa — EAccelerate Fund",
    url: "https://documentaryafrica.org",
    applicationUrl: "https://documentaryafrica.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "documentary-africa-eaccelerate-fund",
  },
  {
    title: "Documentary Africa — grants portal",
    organization: "Documentary Africa — grants portal",
    url: "https://grants.documentaryafrica.org",
    applicationUrl: "https://grants.documentaryafrica.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "documentary-africa-grants-portal",
  },
  {
    title: "Docubox — East African Documentary Film Fund",
    organization: "Docubox — East African Documentary Film Fund",
    url: "https://docubox.org",
    applicationUrl: "https://docubox.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "docubox-east-african-documentary-film-fund",
  },
  {
    title: "Hot Docs-Blue Ice Docs Fund",
    organization: "Hot Docs-Blue Ice Docs Fund",
    url: "https://hotdocs.ca/industry/film-funds/hot-docs-blue-ice-docs-fund",
    applicationUrl: "https://hotdocs.ca/industry/film-funds/hot-docs-blue-ice-docs-fund",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "hot-docs-blue-ice-docs-fund",
  },
  {
    title: "Sundance Institute Documentary Fund",
    organization: "Sundance Institute Documentary Fund",
    url: "https://www.sundance.org",
    applicationUrl: "https://www.sundance.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "sundance-institute-documentary-fund",
  },
  {
    title: "SFFILM Documentary Film Fund",
    organization: "SFFILM Documentary Film Fund",
    url: "https://sffilm.org",
    applicationUrl: "https://sffilm.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "sffilm-documentary-film-fund",
  },
  {
    title: "IDFA Bertha Fund",
    organization: "IDFA Bertha Fund",
    url: "https://www.idfa.nl",
    applicationUrl: "https://www.idfa.nl",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "idfa-bertha-fund",
  },
  {
    title: "Hubert Bals Fund (IFFR)",
    organization: "Hubert Bals Fund (IFFR)",
    url: "https://iffr.com",
    applicationUrl: "https://iffr.com",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "hubert-bals-fund-iffr",
  },
  {
    title: "World Cinema Fund (Berlinale)",
    organization: "World Cinema Fund (Berlinale)",
    url: "https://www.berlinale.de",
    applicationUrl: "https://www.berlinale.de",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "world-cinema-fund-berlinale",
  },
  {
    title: "Doha Film Institute Grants",
    organization: "Doha Film Institute Grants",
    url: "https://www.dohafilminstitute.com",
    applicationUrl: "https://www.dohafilminstitute.com",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "doha-film-institute-grants",
  },
  {
    title: "Durban FilmMart",
    organization: "Durban FilmMart",
    url: "https://www.durbanfilmmart.co.za",
    applicationUrl: "https://www.durbanfilmmart.co.za",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "durban-filmmart",
  },
  {
    title: "Berlinale Talents / Talents Durban",
    organization: "Berlinale Talents / Talents Durban",
    url: "https://www.berlinale-talents.de",
    applicationUrl: "https://www.berlinale-talents.de",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "berlinale-talents-talents-durban",
  },
  {
    title: "Realness Institute",
    organization: "Realness Institute",
    url: "https://www.realness.institute",
    applicationUrl: "https://www.realness.institute",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "realness-institute",
  },
  {
    title: "Catapult Film Fund",
    organization: "Catapult Film Fund",
    url: "https://catapultfilmfund.org",
    applicationUrl: "https://catapultfilmfund.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "catapult-film-fund",
  },
  {
    title: "Chicken & Egg Pictures",
    organization: "Chicken & Egg Pictures",
    url: "https://chickeneggpics.org",
    applicationUrl: "https://chickeneggpics.org",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "chicken-egg-pictures",
  },
  {
    title: "Sørfond (Norwegian South Film Fund)",
    organization: "Sørfond (Norwegian South Film Fund)",
    url: "https://sorfond.no",
    applicationUrl: "https://sorfond.no",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "s-rfond-norwegian-south-film-fund",
  },
  {
    title: "CNC Aide aux cinémas du monde",
    organization: "CNC Aide aux cinémas du monde",
    url: "https://www.cnc.fr",
    applicationUrl: "https://www.cnc.fr",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "cnc-aide-aux-cinemas-du-monde",
  },
  {
    title: "Locarno Open Doors",
    organization: "Locarno Open Doors",
    url: "https://www.locarnofestival.ch",
    applicationUrl: "https://www.locarnofestival.ch",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "locarno-open-doors",
  },
  {
    title: "Encounters South African International Documentary Festival",
    organization: "Encounters South African International Documentary Festival",
    url: "https://encounters.co.za",
    applicationUrl: "https://encounters.co.za",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "encounters-south-african-international-documentary-festival",
  },
  {
    title: "Invisible Borders — Trans-African Road Trip",
    organization: "Invisible Borders — Trans-African Road Trip",
    url: "https://www.invisible-borders.com",
    applicationUrl: "https://www.invisible-borders.com",
    category: "arts_film_media",
    focusText: "Film / documentary fund",
    sourceItemId: "invisible-borders-trans-african-road-trip",
  },
  {
    title: "Africa-Europe Partnerships for Culture — Mobility Grants (Goethe-Institut)",
    organization: "Africa-Europe Partnerships for Culture — Mobility Grants (Goethe-Institut)",
    url: "https://www.goethe.de/prj/aep/en/cal/ssa/mga/img.html",
    applicationUrl: "https://www.goethe.de/prj/aep/en/cal/ssa/mga/img.html",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "africa-europe-partnerships-for-culture-mobility-grants-goethe-institut",
  },
  {
    title: "Nafasi Art Space Residency (Dar es Salaam)",
    organization: "Nafasi Art Space Residency (Dar es Salaam)",
    url: "https://www.nafasiartspace.org/open-call-for-artist-in-residence-2026",
    applicationUrl: "https://www.nafasiartspace.org/open-call-for-artist-in-residence-2026",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "nafasi-art-space-residency-dar-es-salaam",
  },
  {
    title: "Instituto Sacatar (Bahia, Brazil)",
    organization: "Instituto Sacatar (Bahia, Brazil)",
    url: "https://sacatar.org",
    applicationUrl: "https://sacatar.org",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "instituto-sacatar-bahia-brazil",
  },
  {
    title: "Studio Museum in Harlem — Artist-in-Residence",
    organization: "Studio Museum in Harlem — Artist-in-Residence",
    url: "https://www.studiomuseum.org",
    applicationUrl: "https://www.studiomuseum.org",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "studio-museum-in-harlem-artist-in-residence",
  },
  {
    title: "Emergence Pan-African Residency (Casablanca)",
    organization: "Emergence Pan-African Residency (Casablanca)",
    url: "https://amxafrica.com/blog/listing/open-call-for-artists-emergence-pan-african-residency/",
    applicationUrl: "https://amxafrica.com/blog/listing/open-call-for-artists-emergence-pan-african-residency/",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "emergence-pan-african-residency-casablanca",
  },
  {
    title: "Rele Arts Foundation — R2 Space Residency",
    organization: "Rele Arts Foundation — R2 Space Residency",
    url: "https://www.rele.co",
    applicationUrl: "https://www.rele.co",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "rele-arts-foundation-r2-space-residency",
  },
  {
    title: "Absa L'Atelier",
    organization: "Absa L'Atelier",
    url: "https://www.absa.africa",
    applicationUrl: "https://www.absa.africa",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "absa-l-atelier",
  },
  {
    title: "Thami Mnyele Foundation (Amsterdam)",
    organization: "Thami Mnyele Foundation (Amsterdam)",
    url: "https://www.thamimnyele.nl",
    applicationUrl: "https://www.thamimnyele.nl",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "thami-mnyele-foundation-amsterdam",
  },
  {
    title: "DAAD Artists-in-Berlin Program",
    organization: "DAAD Artists-in-Berlin Program",
    url: "https://www.berliner-kuenstlerprogramm.de",
    applicationUrl: "https://www.berliner-kuenstlerprogramm.de",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "daad-artists-in-berlin-program",
  },
  {
    title: "Cité internationale des arts (Paris)",
    organization: "Cité internationale des arts (Paris)",
    url: "https://www.citedesartsparis.fr",
    applicationUrl: "https://www.citedesartsparis.fr",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "cite-internationale-des-arts-paris",
  },
  {
    title: "Rijksakademie (Amsterdam)",
    organization: "Rijksakademie (Amsterdam)",
    url: "https://www.rijksakademie.nl",
    applicationUrl: "https://www.rijksakademie.nl",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "rijksakademie-amsterdam",
  },
  {
    title: "Rockefeller Bellagio Center",
    organization: "Rockefeller Bellagio Center",
    url: "https://www.rockefellerfoundation.org/bellagio-center/",
    applicationUrl: "https://www.rockefellerfoundation.org/bellagio-center/",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "rockefeller-bellagio-center",
  },
  {
    title: "Civitella Ranieri Fellowship",
    organization: "Civitella Ranieri Fellowship",
    url: "https://civitella.org",
    applicationUrl: "https://civitella.org",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "civitella-ranieri-fellowship",
  },
  {
    title: "MacDowell",
    organization: "MacDowell",
    url: "https://www.macdowell.org",
    applicationUrl: "https://www.macdowell.org",
    category: "arts_residencies",
    focusText: "Artist residency / mobility grant",
    sourceItemId: "macdowell",
  },
  {
    title: "UNDP timbuktoo CreativeTech Launchpad",
    organization: "UNDP timbuktoo CreativeTech Launchpad",
    url: "https://www.undp.org/south-africa/press-releases/undp-launches-call-applications-creativetech-startups-join-timbuktoo-launchpad",
    applicationUrl: "https://www.undp.org/south-africa/press-releases/undp-launches-call-applications-creativetech-startups-join-timbuktoo-launchpad",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "undp-timbuktoo-creativetech-launchpad",
  },
  {
    title: "Founders Fund Africa — Creative Economy Accelerator",
    organization: "Founders Fund Africa — Creative Economy Accelerator",
    url: "https://foundersfundafrica.com",
    applicationUrl: "https://foundersfundafrica.com",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "founders-fund-africa-creative-economy-accelerator",
  },
  {
    title: "Africa's Business Heroes (Jack Ma Foundation)",
    organization: "Africa's Business Heroes (Jack Ma Foundation)",
    url: "https://africabusinessheroes.org",
    applicationUrl: "https://africabusinessheroes.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "africa-s-business-heroes-jack-ma-foundation",
  },
  {
    title: "Mandela Washington Fellowship (YALI)",
    organization: "Mandela Washington Fellowship (YALI)",
    url: "https://www.mandelawashingtonfellowship.org",
    applicationUrl: "https://www.mandelawashingtonfellowship.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "mandela-washington-fellowship-yali",
  },
  {
    title: "Obama Foundation Leaders: Africa",
    organization: "Obama Foundation Leaders: Africa",
    url: "https://www.obama.org",
    applicationUrl: "https://www.obama.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "obama-foundation-leaders-africa",
  },
  {
    title: "Westerwelle Foundation Young Founders Programme",
    organization: "Westerwelle Foundation Young Founders Programme",
    url: "https://westerwelle-foundation.com",
    applicationUrl: "https://westerwelle-foundation.com",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "westerwelle-foundation-young-founders-programme",
  },
  {
    title: "Anzisha Prize",
    organization: "Anzisha Prize",
    url: "https://anzishaprize.org",
    applicationUrl: "https://anzishaprize.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "anzisha-prize",
  },
  {
    title: "Acumen East Africa Fellowship",
    organization: "Acumen East Africa Fellowship",
    url: "https://acumen.org",
    applicationUrl: "https://acumen.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "acumen-east-africa-fellowship",
  },
  {
    title: "Cartier Women's Initiative",
    organization: "Cartier Women's Initiative",
    url: "https://www.cartierwomensinitiative.com",
    applicationUrl: "https://www.cartierwomensinitiative.com",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "cartier-women-s-initiative",
  },
  {
    title: "Hult Prize",
    organization: "Hult Prize",
    url: "https://www.hultprize.org",
    applicationUrl: "https://www.hultprize.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "hult-prize",
  },
  {
    title: "Seedstars",
    organization: "Seedstars",
    url: "https://www.seedstars.com",
    applicationUrl: "https://www.seedstars.com",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "seedstars",
  },
  {
    title: "African Culture Fund",
    organization: "African Culture Fund",
    url: "https://www.africanculturefund.net",
    applicationUrl: "https://www.africanculturefund.net",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "african-culture-fund",
  },
  {
    title: "Arts Collaboratory",
    organization: "Arts Collaboratory",
    url: "https://www.artscollaboratory.org",
    applicationUrl: "https://www.artscollaboratory.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "arts-collaboratory",
  },
  {
    title: "DOEN Foundation",
    organization: "DOEN Foundation",
    url: "https://www.doen.nl",
    applicationUrl: "https://www.doen.nl",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "doen-foundation",
  },
  {
    title: "Hivos",
    organization: "Hivos",
    url: "https://hivos.org",
    applicationUrl: "https://hivos.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "hivos",
  },
  {
    title: "Open Society Foundations",
    organization: "Open Society Foundations",
    url: "https://www.opensocietyfoundations.org",
    applicationUrl: "https://www.opensocietyfoundations.org",
    category: "business_creative_entrepreneur",
    focusText: "Business accelerator / leadership fellowship",
    sourceItemId: "open-society-foundations",
  },
  {
    title: "Royal Academy of Engineering — Africa Prize for Engineering Innovation",
    organization: "Royal Academy of Engineering — Africa Prize for Engineering Innovation",
    url: "https://raeng.org.uk",
    applicationUrl: "https://raeng.org.uk",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "royal-academy-of-engineering-africa-prize-for-engineering-innovation",
  },
  {
    title: "GSMA Innovation Fund",
    organization: "GSMA Innovation Fund",
    url: "https://www.gsma.com",
    applicationUrl: "https://www.gsma.com",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "gsma-innovation-fund",
  },
  {
    title: "Google for Startups Accelerator: Africa",
    organization: "Google for Startups Accelerator: Africa",
    url: "https://startup.google.com",
    applicationUrl: "https://startup.google.com",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "google-for-startups-accelerator-africa",
  },
  {
    title: "Village Capital",
    organization: "Village Capital",
    url: "https://vilcap.com",
    applicationUrl: "https://vilcap.com",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "village-capital",
  },
  {
    title: "Aceli Africa",
    organization: "Aceli Africa",
    url: "https://aceliafrica.org",
    applicationUrl: "https://aceliafrica.org",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "aceli-africa",
  },
  {
    title: "VC4A",
    organization: "VC4A",
    url: "https://vc4a.com",
    applicationUrl: "https://vc4a.com",
    category: "tech_nonprofit_tech",
    focusText: "Tech / agri-fintech innovation programme",
    sourceItemId: "vc4a",
  },
  {
    title: "LagosPhoto Festival",
    organization: "LagosPhoto Festival",
    url: "https://www.lagosphotofestival.com",
    applicationUrl: "https://www.lagosphotofestival.com",
    category: "arts_visual_photography",
    focusText: "Photography festival with open calls",
    sourceItemId: "lagosphoto-festival",
  },
  {
    title: "Addis Foto Fest",
    organization: "Addis Foto Fest",
    url: "https://www.addisfotofest.com",
    applicationUrl: "https://www.addisfotofest.com",
    category: "arts_visual_photography",
    focusText: "Photography festival with open calls",
    sourceItemId: "addis-foto-fest",
  },
  {
    title: "Rencontres de Bamako (African Biennale of Photography)",
    organization: "Rencontres de Bamako (African Biennale of Photography)",
    url: "https://www.rencontres-bamako.com",
    applicationUrl: "https://www.rencontres-bamako.com",
    category: "arts_visual_photography",
    focusText: "Photography festival with open calls",
    sourceItemId: "rencontres-de-bamako-african-biennale-of-photography",
  },
  {
    title: "Dak'Art — Biennial of Contemporary African Art",
    organization: "Dak'Art — Biennial of Contemporary African Art",
    url: "https://biennaledakar.org",
    applicationUrl: "https://biennaledakar.org",
    category: "arts_multidisciplinary",
    focusText: "Contemporary art fair / biennial with open calls",
    sourceItemId: "dak-art-biennial-of-contemporary-african-art",
  },
  {
    title: "1-54 Contemporary African Art Fair",
    organization: "1-54 Contemporary African Art Fair",
    url: "https://www.1-54.com",
    applicationUrl: "https://www.1-54.com",
    category: "arts_multidisciplinary",
    focusText: "Contemporary art fair / biennial with open calls",
    sourceItemId: "1-54-contemporary-african-art-fair",
  },
  {
    title: "Mozilla Fellows Program",
    organization: "Mozilla Foundation",
    url: "https://foundation.mofostaging.net/en/what-we-do/grantmaking/fellowship/2026-nominations-request/",
    applicationUrl: "https://foundation.mofostaging.net/en/what-we-do/grantmaking/fellowship/2026-nominations-request/",
    category: "tech_nonprofit_tech",
    focusText:
      "Year-long fellowship (funding, mentorship, platform access) for leaders building better technology futures: privacy protection, AI auditing, climate justice, creator protection, data democratization, open infrastructure.",
    eligibilityText:
      "Track II Independent Fellows track is open to candidates from all countries where Mozilla Foundation can legally make grants, with particular focus on recruiting from the Global Majority (including Africa); self-nominations welcome. Fellows must be able to legally enter a grant agreement with a US-based 501c3 and receive payment via ACH/wire from the US. Track I Embedded Fellows is limited to Kenya, South Africa, Brazil, MENA, Mexico, UK, US and EU.",
    amountText: "Track I: $100,000 total ($75,000 stipend + $25,000 project budget). Track II: $125,000 total ($100,000 stipend + $25,000 project budget)",
    windowText: "2026 cohort nominations closed January 30, 2026; future deadlines communicated by email, next cycle not yet announced",
    sourceItemId: "mozilla-fellows-program",
  },
  {
    title: "AU Digital and Innovation Fellowship Programme",
    organization: "African Union Commission",
    url: "https://www.au.int/en/pressreleases/20260218/au-call-applications-3rd-cohort-digital-innovation-fellowship",
    applicationUrl: "https://enpact.org/au-digital-innovation-fellowship-positions/",
    category: "tech_nonprofit_tech",
    focusText:
      "12-month immersive fellowship embedding young technical professionals within AU institutions, across tracks including data analytics, digital product management, ERP systems, full-stack development, HR digital systems and business analysis.",
    eligibilityText:
      "Open to citizens of African Union member states (including Tanzania), under age 35, with a bachelor's degree in a relevant technical field. Women and persons with disabilities are especially encouraged to apply.",
    amountText: "Monthly stipend, equipment budget, learning budget, plus bootcamp and mid-term delegation visit",
    windowText: "3rd cohort applications closed March 1, 2026; watch for the next cohort announcement",
    sourceItemId: "au-digital-and-innovation-fellowship-programme",
  },
  {
    title: "Building Beyond Fellowship",
    organization: "Prince Claus Fund",
    url: "https://princeclausfund.nl/awards-and-programmes/fellows-award/building-beyond",
    applicationUrl: "https://princeclausfund.nl/awards-and-programmes/fellows-award/building-beyond",
    category: "arts_residencies",
    focusText:
      "Multi-disciplinary fellowship for mid-career artists/cultural practitioners (architecture, design, spatial practice) exploring how communities relate to each other and public space in their cities.",
    eligibilityText:
      "Open to applicants from, living and working in eligible African countries, explicitly including Tanzania. Requires roughly 7-15 years of professional experience and an individual creative practice (not arts managers/academics without their own practice); fluent English required.",
    amountText: "EUR 10,000 per fellow plus mentorship from Senior Fellows",
    windowText:
      "Cycle 5 applications closed August 13, 2025; from 2025/2026 the program is run solely by Prince Claus Fund and next cycle dates are not yet announced, contact e.vanschie@princeclausfund.nl for updates",
    sourceItemId: "building-beyond-fellowship-prince-claus-fund",
  },
  {
    title: "STIAS Fellowships (Individual, Team, Iso Lomso, Artist-in-Residence)",
    organization: "Stellenbosch Institute for Advanced Study (STIAS)",
    url: "https://www.stias.ac.za/fellowships/apply/",
    applicationUrl: "https://www.stias.ac.za/fellowships/apply/",
    category: "arts_residencies",
    focusText:
      "Residential fellowships for dedicated research/creative time: Individual and Team Fellowships (any discipline, any career stage, worldwide), Iso Lomso Fellowship (early-to-mid-career African researchers), and Artist-in-Residence (any discipline, no geographic restriction).",
    eligibilityText:
      "Individual, Team and Artist-in-Residence fellowships have no country-of-origin restriction. Iso Lomso is restricted to African nationals or those affiliated with African institutions (Tanzania qualifies), doctorate earned within the preceding 8 years, applicant under age 42.",
    amountText:
      "Iso Lomso: economy airfare, accommodation, monthly stipend, office space, library access, childcare subsidies, conference/residency support. Other tracks: stipend details vary, contact STIAS.",
    windowText:
      "Individual/Team/Artist-in-Residence: deadline October 31, 2026 (for 2028 1st semester). Iso Lomso: next call opens October 15, 2026, deadline February 15, 2027.",
    sourceItemId: "stias-fellowships",
  },
  {
    title: "Block Builder Fellowship",
    organization: "Block, Inc.",
    url: "https://block.xyz/builder-fellowship",
    applicationUrl: "https://block.xyz/builder-fellowship",
    category: "tech_nonprofit_tech",
    focusText:
      "6-month, fully-paid, remote-first fellowship placing emerging AI/design/engineering talent within Block's teams (Square, Cash App, Afterpay, TIDAL, Proto, Bitkey).",
    eligibilityText:
      "Remote-first program open worldwide to applicants already authorized to work in their own country of residence (no visa sponsorship or relocation required). Engineering track requires age 18+; design track considered case-by-case from age 14+. Applicants must show proof of building (code, prototypes, design work, or creative projects).",
    amountText: "Fully paid, 6-month program with benefits and equipment provided",
    windowText:
      "Applications currently closed for both the design and engineering tracks; sign up on the program page for notice of the next cycle.",
    sourceItemId: "block-builder-fellowship",
  },
  {
    title: "MOSS Foundational Technology Track",
    organization: "Mozilla Open Source Support (MOSS)",
    url: "https://www.mozilla.org/en-US/moss/foundational-technology/",
    applicationUrl: "https://mozilla.fluxx.io/apply/MOSS",
    category: "tech_nonprofit_tech",
    focusText:
      "Grants for open source/free software projects that Mozilla itself relies on or uses in its infrastructure.",
    eligibilityText:
      "The project's home can be anywhere in the world where Mozilla can make payment without undue burden, so Tanzania and other African locations are eligible. Application must be filed jointly by the project lead and an established Mozilla employee sponsor; legally organized projects are preferred over unaffiliated individuals.",
    amountText: "USD 10,000 to USD 250,000",
    windowText: "Rolling, considered monthly; typical response time about two months, no fixed deadline",
    sourceItemId: "moss-foundational-technology-track",
  },
  {
    title: "SYFoA Leadership Fellowship",
    organization: "Story-Your-Future of Africa (SYFoA)",
    url: "https://syfoa.chiefmoses.org/wp/apply-2/",
    applicationUrl: "https://syfoa.chiefmoses.org/wp/apply-2/",
    category: "community_civic",
    focusText:
      "Six-month leadership development fellowship for young African leaders, welcoming applicants from social development, entrepreneurship, governance, education, technology, creative industries and community advocacy.",
    eligibilityText:
      "Open to applicants currently residing in an African country, including Tanzania. Ages 18-30 (as of September 30, 2026), English proficiency, full availability for the six-month program, ability to attend an in-person residency in Accra, Ghana, and a valid passport through June 2027.",
    amountText: null,
    windowText: "Deadline: September 30, 2026",
    sourceItemId: "syfoa-leadership-fellowship",
  },
  {
    title: "Artizen House Zanzibar Residency",
    organization: "Artizen House Zanzibar",
    url: "https://artizenhousezanzibar.com/",
    applicationUrl: "https://artizenhousezanzibar.com/apply",
    category: "arts_residencies",
    focusText:
      "A recurring small-group creative residency embedded inside larger pop-up cities and gatherings, based in Zanzibar, Tanzania, bringing a handful of creators together to make work in the same room.",
    eligibilityText:
      "Based in Zanzibar, Tanzania, so Tanzanian applicants are inherently eligible; the organization's public pages do not publish full eligibility, cost, or funding details, confirm directly on their apply page before relying on this listing.",
    amountText: null,
    windowText: null,
    sourceItemId: "artizen-house-zanzibar-residency",
  },
  {
    title: "ADW Future Design Fellowship",
    organization: "Asia Design Week / ADW Future Design Scholars Program",
    url: "https://www.adwscholar.com/2026-fellowship/",
    applicationUrl: "https://www.adwscholar.com/2026-fellowship/",
    category: "arts_multidisciplinary",
    focusText:
      "Independent, design-centered interdisciplinary research fellowship; 2026 theme is Design Beyond Boundaries: Convergence, Creativity, and Sustainable Innovation.",
    eligibilityText:
      "Welcomes applicants worldwide with no nationality restriction, so Tanzania and other African applicants are eligible. Applicants should typically hold a doctorate or equivalent advanced research credentials.",
    amountText: "Up to USD 100,000 for up to 12 months, including a monthly stipend of USD 7,500",
    windowText: "2026 cycle closed May 31, 2026; award coordination underway, next cycle not yet announced",
    sourceItemId: "adw-future-design-fellowship",
  },
];
